### DISCUSSION TITLE
WV income tax difference with TAXSIM35

### DISCUSSION THREAD

**Discussion by martinholmer** [PolicyEngine/policyengine-us#3939] [Q&A]
The following integration test fails. It is not yet known whether the
tax logic problem is in TAXSIM35 or in the current PEUS code, or
whether there are problems in both models. This topic is meant to
facilitate discussion of why this test fails, primarily by reporting
the results of hand calculations required to fill out the relevant tax
form.

```
- name: Tax unit with taxsimid 99997 in k21.its.csv and k21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 72
        employment_income: 8010
        qualified_dividend_income: 4010
        taxable_interest_income: 11010
        short_term_capital_gains: 3010
        long_term_capital_gains: 1010
        rental_income: 3010
        taxable_private_pension_income: 9000
        social_security_retirement: 1000
        real_estate_taxes: 8000
        mortgage_interest: 3000
        self_employment_income: 38010
        business_is_qualified: true
        business_is_sstb: true
        w2_wages_from_qualified_business: 100e6
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person2:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person3:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person4:
        age: 16
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4]
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
        ca_use_tax: 0  # not in TAXSIM35
        il_use_tax: 0  # not in TAXSIM35
        nm_2021_income_rebate: 0  # not in TAXSIM35
        nm_additional_2021_income_rebate: 0  # not in TAXSIM35
        nm_supplemental_2021_income_rebate: 0  # not in TAXSIM35
        ny_supplemental_eitc: 0  # not in TAXSIM35
        ok_use_tax: 0  # not in TAXSIM35
        pa_use_tax: 0  # not in TAXSIM35
        vt_renter_credit: 0  # not in TAXSIM35
        tax_unit_itemizes: False
        state_income_tax: 2729.08
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2, person3, person4]
        state_fips: 54  # WV
  output:  # expected results from patched TAXSIM35 2024-02-18 version
    wv_income_tax: 1729.08
```
