### DISCUSSION TITLE
MD income tax difference with TAXSIM35

### DISCUSSION THREAD

**Discussion by martinholmer** [PolicyEngine/policyengine-us#4115] [Q&A]
The following integration test fails. It is not yet known whether the
tax logic problem is in TAXSIM35 or in the current PEUS code, or
whether there are problems in both models. This topic is meant to
facilitate discussion of why this test fails, primarily by reporting
the results of hand calculations required to fill out the relevant tax
form.

**SEE HINTS BELOW THE INTEGRATION TEST**

```
- name: Tax unit with taxsimid 85510 in p21.its.csv and p21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 53
        employment_income: 12010
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1]
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
        ca_use_tax: 0  # not in TAXSIM35
        il_use_tax: 0  # not in TAXSIM35
        nm_2021_income_rebate: 0  # not in TAXSIM35
        nm_additional_2021_income_rebate: 0  # not in TAXSIM35
        nm_supplemental_2021_income_rebate: 0  # not in TAXSIM35
        ny_supplemental_eitc: 0  # not in TAXSIM35
        ok_use_tax: 0  # not in TAXSIM35
        pa_use_tax: 0  # not in TAXSIM35
        vt_renter_credit: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1]
        state_fips: 24  # MD
  output:  # expected results from patched TAXSIM35 2024-03-08 version
    md_income_tax: -249.60
```

**Here is how TAXSIM and PEUS differ on how this case should fill out the form:**
```
                  TAXSIM     PEUS
itax_pre_credits  280.40   280.40 md_income_tax_before_credits

    eitc_nonref   280.40     0.00
    povlinec        0.00   280.40 md_poverty_line_credit
    eitc_ref      249.60   530.00 md_single_childless_eitc

total_credits     530.00   810.40

itax             -249.60  -530.00 md_income_tax
```
