### DISCUSSION TITLE
MT income tax difference with TAXSIM35

### DISCUSSION THREAD

**Discussion by martinholmer** [PolicyEngine/policyengine-us#4270] [Q&A]
Below is an integration test that generates taxable income amounts when the couple is considering filing separately on the same form that are different from TAXSIM35.
Here is the relevant trace output (using 0.711.6 version):

```shell
(policyengine-us) MT% grep _agi e21-id22630.trace | head -1
  mt_agi<2021, (default)> = [ 5505. 32515.]
(policyengine-us) MT% grep exemptions_indiv e21-id22630.trace | head -1
  mt_personal_exemptions_indiv<2021, (default)> = [2580. 2580.]
(policyengine-us) MT% grep standard_deduction_indiv e21-id22630.trace | head -1
  mt_standard_deduction_indiv<2021, (default)> = [2140. 4830.]
(policyengine-us) MT% grep taxable_income_indiv e21-id22630.trace | head -1 
  mt_taxable_income_indiv<2021, (default)> = [ 2925. 22965.]
```

The form suggests to me that the taxable incomes in this case should be AGI minus exemptions minus standard deduction, but that is not what Policyengine-US generates.  The generated AGI, exemptions, and standard deductions amounts are exactly the same as those generated by TAXSIM35.

Here is the integration test that generated the above trace information:

```yaml
- name: Tax unit with taxsimid 22630 in e21.its.csv and e21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 59
        taxable_interest_income: 5505.0
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person2:
        age: 59
        employment_income: 27010
        taxable_interest_income: 5505.0
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2]
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
        ca_use_tax: 0  # not in TAXSIM35
        il_use_tax: 0  # not in TAXSIM35
        nm_2021_income_rebate: 0  # not in TAXSIM35
        nm_additional_2021_income_rebate: 0  # not in TAXSIM35
        nm_supplemental_2021_income_rebate: 0  # not in TAXSIM35
        ny_supplemental_eitc: 0  # not in TAXSIM35
        ok_use_tax: 0  # not in TAXSIM35
        pa_use_tax: 0  # not in TAXSIM35
        vt_renter_credit: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2]
        state_fips: 30  # MT
  output:  # expected results from patched TAXSIM35 2024-03-21 version
    mt_income_tax: 1140.90
```
