### DISCUSSION TITLE
Montana `mt_federal_income_tax_deduction` can not be allocated properly as we do not calculate `income_tax_before_refundable_credits` on the person level

### DISCUSSION THREAD

**Discussion by PavelMakarchuk** [PolicyEngine/policyengine-us#4425] [Q&A]
The following integration test illustrates the issue:
```yaml
- name: Tax unit with taxsimid 34790 in e21.its.csv and e21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 33
        employment_income: 7_010
        taxable_interest_income: 5_505
      person2:
        age: 33
        employment_income: 136_010
        taxable_interest_income: 5_505
      person3:
        age: 16
      person4:
        age: 16
      person5:
        age: 16
      person6:
        age: 16
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4, person5, person6]
        premium_tax_credit: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4, person5, person6]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2, person3, person4, person5, person6]
        state_fips: 30  # MT
  output:  # expected results from patched TAXSIM35 2024-03-09 version
    mt_agi: [12_515, 141_515, 0, 0, 0, 0]
    mt_standard_deduction_indiv: [2_503, 4_830, 0, 0, 0, 0]
    mt_income_tax: 7_812.64
```
    
Here the tax unit is eligible for a $10,000 federal income tax deduction, which we currently allocate to the head of the household as it is dependent on the tax unit level input of `income_tax_before_refundable_credits`. 
    
In this case, the entire deduction amount should be attributed to the spouse as they would be filing separately on the same return. We can't prorate based on Montana AGI or federal AGI as this will not attribute 100% to the spouse. 
    
@MaxGhenis I wonder if we have a person level equivalent to `income_tax_before_refundable_credits` or there is any way we can circumvent this issue. 
    @martinholmer FYI

**Comment by martinholmer** [comment]
@PavelMakarchuk,  TAXSIM35 logic in early March reflected our (mis)understanding that dependent exemptions and all itemized deductions could be allocated in any way between a married couple who is filing separately.

But now we know that it much more complicated:  the federal income tax itemized deduction amount cannot be allocated in any way.   The MT instructions seem to imply that one needs to know the couple's federal income tax before refundable credits allocated between them.   But as your discussion in topic #4225 indicates, there is no such federal variable.   My own preliminary thinking leads me to believe that constructing such a federal variable would be complex and force the introduction of "rules" that have no basis in federal law, all for the needs of one small-state income tax.   It seems to me the best approach is to introduce these ad hoc "rules" in the MT code because they are need only there.

The current (2024-04-21) version of TAXSIM35 has been patched to use the `mt_agi` variable to allocate the federal income tax itemized deduction amount.

Below I show how the new TAXSIM35 treats the test case shown above (which if different from early March), and how that treatment compares with that of Policyengine-US 0.743.1.   First the test case:

```
- name: Tax unit with taxsimid 34790 in e21.its.csv and e21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 33
        employment_income: 7010
        taxable_interest_income: 5505.0
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person2:
        age: 33
        employment_income: 136010
        taxable_interest_income: 5505.0
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person3:
        age: 16
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person4:
        age: 16
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person5:
        age: 16
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person6:
        age: 16
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4, person5, person6]
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
        ca_use_tax: 0  # not in TAXSIM35
        il_use_tax: 0  # not in TAXSIM35
        nm_2021_income_rebate: 0  # not in TAXSIM35
        nm_additional_2021_income_rebate: 0  # not in TAXSIM35
        nm_supplemental_2021_income_rebate: 0  # not in TAXSIM35
        ny_supplemental_eitc: 0  # not in TAXSIM35
        ok_use_tax: 0  # not in TAXSIM35
        pa_use_tax: 0  # not in TAXSIM35
        vt_renter_credit: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4, person5, person6]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2, person3, person4, person5, person6]
        state_fips: 30  # MT
  output:  # expected results from patched TAXSIM35 2024-04-21 version
    mt_income_tax: 8078.93
```

Here is trace output from TAXSIM35:

```
   agiJ              154030.00     
   stdedJ,xitdedJ      9660.00     10000.00     
   deducJ,exempJ      10000.00     15480.00
   taxincJ,itaxbcJ   128550.00      8270.75
   
   agiH,agiW          12515.00    141515.00
   stdedH,stdedW       2503.00      4830.00     
   itdedH,itdedW        812.50      5000.00
   exempH,exempW       2580.00     12900.00
   taxincHs,taxincWs   7432.00    123785.00
   taxincHi,taxincWi   9122.50    123615.00
   itaxbcH,itaxbcW      136.96      7941.97
   itaxbcJ,itaxbcS     8270.75      8078.93
   
   files separately using standard deduction
   itaxbc                     8078.93
```

And here part of the trace output from Policyengine-US that shows differences with TAXSIM35:

```
mt_agi                  [ 12515. 141515.]  
mt_standard_ded_indiv   [  2503.   4830.] 
mt_itemized_ded_indiv   [ 10000.      0.] 
mt_taxable_income_indiv [     0. 128615.] 

```

The first two lines agree with TAXSIM35, but the second two line disagree.
