### DISCUSSION TITLE
LA income tax difference with TAXSIM35

### DISCUSSION THREAD

**Discussion by martinholmer** [PolicyEngine/policyengine-us#4517] [Q&A]
The following integration test fails. It is not yet known whether the
tax logic problem is in TAXSIM35 or in the current PEUS code, or
whether there are problems in both models. This topic is meant to
facilitate discussion of why this test fails, primarily by reporting
the results of hand calculations required to fill out the relevant tax
form.

```
- name: Tax unit with taxsimid 6058 in g21.its.csv and g21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 72
        employment_income: 20010
        taxable_interest_income: 11010
        taxable_private_pension_income: 9000
        social_security_retirement: 22000
        rent: 8000
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person2:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person3:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person4:
        age: 16
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4]
        tax_unit_childcare_expenses: 9000
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
        ca_use_tax: 0  # not in TAXSIM35
        il_use_tax: 0  # not in TAXSIM35
        nm_2021_income_rebate: 0  # not in TAXSIM35
        nm_additional_2021_income_rebate: 0  # not in TAXSIM35
        nm_supplemental_2021_income_rebate: 0  # not in TAXSIM35
        ny_supplemental_eitc: 0  # not in TAXSIM35
        ok_use_tax: 0  # not in TAXSIM35
        pa_use_tax: 0  # not in TAXSIM35
        vt_renter_credit: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2, person3, person4]
        state_fips: 22  # LA
  output:  # expected results from patched TAXSIM35 2024-05-07 version
    la_income_tax: 228.70
```

Here is the high-level difference between the model results:
```
TAXSIM35 SITax Summary:
fedAGI          58720.00    58720.00 adjusted_gross_income
staAGI          34020.00    35829.77 la_agi                DIFF=1809.77
```

The models differ on by how much the $24,700 in exempt income should be reduced.

PEUS reduces exempt income by $1,809.77.   I have no idea what is involved in those calculations because the formula is long and so there are no intermediate global variables that appear in the PEUS trace output.

TAXSIM35 does not reduce exempt income.  Here is the debugging trace output corresponding to the 2021 LA Schedule E:
```
   socsec penexc   18700.000524520874        6000.0000000000000        
   ftsub1,ftsub2   2425.0001311302185        0.0000000000000000     
   FED_agi,FED_tax   58720.001524520878       -197.59993705749366     
   subtr ftsub   24700.000524520874        0.0000000000000000     
   LA_agi   34020.001000000004     
```
