### DISCUSSION TITLE
Why do we project that removing the age limit bump from the ARPA CTC *raises* the cost?

### DISCUSSION THREAD

**Discussion by MaxGhenis** [PolicyEngine/policyengine-us#4902] [Q&A]
With the ECPS in 2025, we project that:
1. [Raising the CTC age limit from 16 to 17 costs $6B](https://policyengine.org/us/policy?reform=63573&focus=policyOutput.policyBreakdown&region=enhanced_us&timePeriod=2025&baseline=2)
1. [The ARPA CTC (plus the Harris baby bonus) costs $117.4B](https://policyengine.org/us/policy?reform=63575&focus=policyOutput.policyBreakdown&region=enhanced_us&timePeriod=2025&baseline=2)
1. [(2) but without the age limit increase costs $118.1B](https://policyengine.org/us/policy?reform=63574&focus=policyOutput.policyBreakdown&region=enhanced_us&timePeriod=2025&baseline=2)
2. [Normal ARPA CTC restoration costs $111.0B](https://policyengine.org/us/policy?reform=63586&focus=policyOutput.policyBreakdown&region=enhanced_us&timePeriod=2025&baseline=2)
3. [Normal ARPA CTC restoration without the age limit increase costs $111.7](https://policyengine.org/us/policy?reform=63587&focus=policyOutput.policyBreakdown&region=enhanced_us&timePeriod=2025&baseline=2)

**Comment by MaxGhenis** [comment]
The ARPA CTC amount is a scale parameter that by default goes up to 17, so the normal CTC should not be necessary.

However, when not setting the normal CTC amount, a we observe an excessively high impact of ARPA on a household with a 17-year-old child. In the income range where they would receive the non-refundable ODC, ARPA should provide them $2,500; however, it is [instead $3,000](https://policyengine.org/us/household?reform=63574&focus=householdOutput.earnings&region=enhanced_us&timePeriod=2025&baseline=2&household=46605):
<img width="786" alt="image" src="https://github.com/user-attachments/assets/5c85685e-3315-4a72-8d43-02202e394f0f">

Setting the age maximum [fixes this](https://policyengine.org/us/household?reform=63575&focus=householdOutput.earnings&region=enhanced_us&timePeriod=2025&baseline=2&household=46605):
<img width="798" alt="image" src="https://github.com/user-attachments/assets/f8585ea3-9a85-40c4-a44b-8fcba8745461">

Adding a 10-year-old child to the household produces these:

[No base age change:](https://policyengine.org/us/household?reform=63574&focus=householdOutput.earnings&region=enhanced_us&timePeriod=2025&baseline=2&household=46607)
![image](https://github.com/user-attachments/assets/6a4cdd5e-263e-4c92-a732-159737cb4a95)

[With base age change:](https://policyengine.org/us/household?reform=63575&focus=householdOutput.earnings&region=enhanced_us&timePeriod=2025&baseline=2&household=46607)
![image](https://github.com/user-attachments/assets/b73ec4e0-fedc-4c51-ba70-fa12ddef25eb)

The base age change correctly gets the higher-income household a benefit since they'd be eligible for the normal 17yo CTC.

More calculations in [this notebook](https://colab.research.google.com/drive/1-E6ZaS0EBfF2KHmtbintNhfZea26IW1d#scrollTo=uc8F3W_dmoWt).

So some thoughts on where the bug could be:
1. In the `ctc_qualifying_child` variable: The age limit is determined by `parameters(period).gov.irs.credits.ctc.amount.base.thresholds[-1]`. If this isn't being updated correctly when ARPA rules are applied, it could cause issues.
2. In the `ctc_child_individual_maximum` and `ctc_child_individual_maximum_arpa` variables: These calculate the maximum CTC amount for children. The bug might be in how these are being combined or prioritized.
3. In the `ctc_maximum_with_arpa_addition` variable: This adds the ARPA addition to the regular maximum. If the regular maximum is being calculated incorrectly when the age limit is changed, it could lead to the behavior you're seeing.

After a deep session with Claude, it suggested:

After reviewing the existing tests, I can suggest some additional tests to cover more scenarios and edge cases. Here are some new test cases we could add:

1. Test for age extension (17 to 18):
   ```yaml
   - name: CTC for 17-year-old with age extension
     period: 2024
     input:
       people:
         child:
           age: 17
           is_tax_unit_dependent: true
       tax_units:
         tax_unit:
           members: [child]
     output:
       ctc_qualifying_child: [True]
       ctc_child_individual_maximum: 2000
   ```

2. Test ARPA phase-out with age extension:
   ```yaml
   - name: ARPA phase-out with age extension for high income
     period: 2024
     input:
       people:
         parent:
           age: 40
           employment_income: 300000
         child:
           age: 17
           is_tax_unit_dependent: true
       tax_units:
         tax_unit:
           members: [parent, child]
     output:
       ctc: 1500  # Partial credit due to phase-out
   ```

3. Test interaction between regular CTC and ARPA addition:
   ```yaml
   - name: Interaction between regular CTC and ARPA addition
     period: 2024
     input:
       people:
         parent:
           age: 40
           employment_income: 100000
         child1:
           age: 5
           is_tax_unit_dependent: true
         child2:
           age: 17
           is_tax_unit_dependent: true
       tax_units:
         tax_unit:
           members: [parent, child1, child2]
     output:
       ctc_maximum: 4000  # 2000 for each child
       ctc_arpa_addition: 1600  # 1600 extra for child under 6
       ctc: 5600  # Total CTC
   ```

4. Test refundability with age extension:
   ```yaml
   - name: Refundability with age extension for low income
     period: 2024
     input:
       people:
         parent:
           age: 40
           employment_income: 20000
         child:
           age: 17
           is_tax_unit_dependent: true
       tax_units:
         tax_unit:
           members: [parent, child]
     output:
       ctc: 2000
       refundable_ctc: 1500  # Assuming $1500 is still the refundable limit
   ```

5. Test phase-out threshold changes:
   ```yaml
   - name: Phase-out threshold for married filing jointly
     period: 2024
     input:
       people:
         parent1:
           age: 40
           employment_income: 390000
         parent2:
           age: 40
           employment_income: 10000
         child:
           age: 10
           is_tax_unit_dependent: true
       tax_units:
         tax_unit:
           members: [parent1, parent2, child]
           filing_status: JOINT
     output:
       ctc_phase_out_threshold: 400000
       ctc: 2000  # Full credit just before phase-out
   ```

6. Test multiple children with different ages:
   ```yaml
   - name: Multiple children with different ages under ARPA rules
     period: 2024
     input:
       people:
         parent:
           age: 40
           employment_income: 100000
         child1:
           age: 5
           is_tax_unit_dependent: true
         child2:
           age: 10
           is_tax_unit_dependent: true
         child3:
           age: 17
           is_tax_unit_dependent: true
       tax_units:
         tax_unit:
           members: [parent, child1, child2, child3]
     output:
       ctc_qualifying_children: 3
       ctc_maximum: 6000  # 2000 * 3
       ctc_arpa_addition: 1600  # Extra for child under 6
       ctc: 7600  # Total CTC
   ```

These additional tests cover various scenarios including the age extension, interactions between regular CTC and ARPA additions, phase-out thresholds, and multiple children scenarios. They should help ensure that the CTC calculations are correct across different family compositions and income levels, especially with the age extension in place.
