### ISSUE TITLE
Fix MA short-term capital gain taxation problem

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#1186]
More than three-quarters of the **s21** sample cases have MA tax differences when compared to TAXSIM35.  Rather than pick one out of the sample, I have hand-specified a very simple case that illustrates the problem: short-term capital gains are being incorrectly taxed at 5% instead of 12%.

First, I show the TAXSIM35 results for this case, then the YAML test file for this case, and finally the test results, which show a $700 MA income tax difference.

Here is the case in TAXSIM35:
```
NBER TAXSIM Model v35 (07/21/22) With TCJA
 State law coded through           0
 Later state laws extrapolated from           0
 Marginal tax rate wrt taxpayer earnings.

 Input Data:                   
      1. Record ID:                       1.
      2. Tax Year:                 2021.00
      3. State Code:                 22.00
      4. Marital Status:              1.00 Single  
    5-6. Age (Txpyr/Spouse):         40.00       0.00
      7. Dependent Exemptions:        0.00
   8-10. #deps for CCC/EIC/CTC:       0.00       0.00       0.00
  11-12. Wages (Txpyr/Spouse):    40000.00       0.00
 11a12a Self-employment income:       0.00       0.00
     13. Dividend Income:             0.00
     14. Interest Received:       20000.00
     15. Short Term Gains:        10000.00
     16. Long Term Gains:             0.00
     17. Other Property:              0.00
     18. Other Non-Property:          0.00
     19. Taxable Pensions:            0.00
     20. Gross Social Security:       0.00
     21. Tot/Txpy/Spouse UI   :       0.00       0.00       0.00
     22. Non-taxable Transfers:       0.00
     23. Rent Paid:                   0.00
     24. Property Taxes Paid:         0.00
     25. Other Itemized Deds:         0.00
     26. Child Care Expenses:         0.00
     27. Mortgage Interest:           0.00
     28. S-Corp profits:              0.00
  29 31. Txpy/Spous QBI w/o PO:       0.00       0.00
  30 32. Txpy/Spouse SSTB w PO:       0.00       0.00
  
 Basic Output:               
      1. Record ID:                1.                            
      2. Year:                           2021
      3. State (SOI code):                 22        Massachusetts       
      4. Federal IIT Liability:       6987.50
      5. State IIT Liability:         3875.00
      6. SS Payroll Tax Liability:    6120.00
 Marginal Rates wrt  Earner
      7. Federal Marginal Rate:         22.00
      8. State Marginal Rate:            5.00
      9. Taxpayer SS Rate:              15.30
                                  
 Federal Tax Calculation:              Base        + $1
     10. Federal AGI                 70000.00    70001.00
     11. UI in AGI 1979+                 0.00        0.00
     12. Social Security in AGI 84       0.00        0.00
     13. Zero Bracket Amount         12550.00    12550.00
     14. Personal Exemptions             0.00        0.00
     15. Exemption Phaseout 1991+        0.00        0.00
     16. Deduction Phaseout 1991+        0.00        0.00
     17. Deductions allowed              0.00        0.00
         QBI deduction                   0.00        0.00
     18. Federal Taxable Income      57450.00    57451.00
     19. Federal Regular Tax          8387.50     8387.72
     20. Exemption Surtax 1988-96        0.00        0.00
     21. General Tax Credit 1975-8       0.00        0.00
     22. Child Tax Credit*17/22 98       0.00        0.00
     23  Refundable Part                 0.00        0.00
     24. Child Care Credit 1076+         0.00        0.00
     25. Earned Income Credit 1975       0.00        0.00
     26. Alternative Min Income:     70000.00    70001.00
     27. AMT                             0.00        0.00
     28. Income Tax Before Credits    8387.50     8387.72
     29. FICA                         6120.00     6120.15
         Taxpayer share of FICA       3060.00     3060.08

 State Tax Calculation:      
     30. Household Income            70000.00    70001.00
     31. Imputed Rent                    0.00        0.00
     32. AGI                         70000.00    70001.00
     33. Exemptions                   4400.00     4400.00
     34. Standard Deduction              0.00        0.00
     35. Itemized Deductions             0.00        0.00
     36. Taxable Income              63500.00    63501.00
     37. Property Tax Credit             0.00        0.00
     38. Child Care Credit               0.00        0.00
     39. EIC                             0.00        0.00
     40. Total Credits                   0.00        0.00
     41. Bracket Rate                    5.00        5.00
         State Tax after Credits      3875.00     3875.05
```

Here is the YAML test file:
```
- name: Tax unit with taxsimid 0 from s21.its.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 40
        employment_income: 40000
        taxable_interest_income: 20000
        short_term_capital_gains: 10000
        ssi: 0
        state_supplement: 0
        wic: 0
        ma_covid_19_essential_employee_premium_pay_program: 0
    spm_units:
      spm_unit:
        members: [person1]
        snap: 0
        tanf: 0
    tax_units:
      tax_unit:
        members: [person1]
        premium_tax_credit: 0
    households:
      household:
        members: [person1]
        state_code: MA
  output:
    ma_income_tax: 3875.00
```

And finally, here are the test results:
```
(openfisca-us) MA% openfisca-us test s21-id0.test.yaml
---[SNIP]---
s21-id0.test.yaml F
---[SNIP]---
  Test 'Tax unit with taxsimid 0 from s21.its.csv':
    ma_income_tax@2021: [3175.] differs from 3875.0
      with an absolute margin [700.] > 0.01
---[SNIP]---
FAILED s21-id0.test.yaml::
---[SNIP]---
```
