### ISSUE TITLE
Incorrect calculation of portion of social security benefits that are taxable

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#1273]
The formulas that compute the portion of social security benefits that are included in AGI are not correct because they omit `tax_exempt_interest_income` from the modified AGI used to compute taxable social security benefits.   That the `tax_exempt_interest_income` amount should be included in the modified AGI is made clear many places, with the this [SSA webpage](https://www.ssa.gov/benefits/retirement/planner/taxes.html) being the most clear.

Here is a simple test case that illustrates the problem:
```
- name: Tax unit with just tax-exempt interest and social security as income.
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 70
        tax_exempt_interest_income: 50000
        social_security: 60000
        ssi: 0  # not in USI-Tax-Analyzer
        state_supplement: 0  # not in USI-Tax-Analyzer
        wic: 0  # not in USI-Tax-Analyzer
    spm_units:
      spm_unit:
        members: [person1]
        snap: 0  # not in USI-Tax-Analyzer
        tanf: 0  # not in USI-Tax-Analyzer
    tax_units:
      tax_unit:
        members: [person1]
        premium_tax_credit: 0  # not in USI-Tax-Analyzer
    households:
      household:
        members: [person1]
  output:  # expected results from USI-Tax-Analyzer 2.35.0 version
    taxsim_tfica: 0.00
    income_tax: 1923.00
```

TAXSIM35 does not have an input variable that corresponds to `tax_exempt_interest_income` so we cannot use that model for comparison.  The USI-Tax-Analyzer model has been used to generate the expected `income_tax` value of $1923.  PolicyEngine US (0.177.3 version) generates the following test result:

Here are the test results for the above YAML test file:
```
================================= FAILURES ===================================
_______________________________ test session _________________________________
/Users/mrh/work/Policy-Engine-US/US/issue1273.yaml:
  Test 'Tax unit with just tax-exempt interest and social security as income.':
    income_tax@2021: [-1400.] differs from 1923.0
                     with an absolute margin [3323.] > 0.01
========================= short test summary info ============================
FAILED issue1273.yaml::
============================ 1 failed in 0.87s ===============================
```
