### ISSUE TITLE
American Opportunity Credit bug

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#1310]
It appears as if the `non_refundable_american_opportunity_credit` variable is never calculated, and therefore, the total `american_opportunity_credit` amount is not being correctly split into refundable and non-refundable parts.    This appears to be so for two reasons: (1) that variable does not appear in test trace output, and (2) the test case below indicates that the 0.129.2 version of OpenFisca-US is producing questionable American Opportunity Credit (AOC) amounts.   Below I show the YAML file containing the test case and below that show some test results.

Here is the test file:
```
# OpenFisca-US test file derived from m21.ita.csv and m21.ota.csv files
- name: Tax unit with recid 99970 from m21.ita.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 27
        ssi: 0
        state_supplement: 0
        wic: 0
        employment_income: 64000
        qualified_tuition_expenses: 11000
        is_eligible_for_american_opportunity_credit: 1
      person2:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 20
        ssi: 0
        state_supplement: 0
        wic: 0
    spm_units:
      spm_unit:
        members: [person1, person2]
        snap: 0
        tanf: 0
    tax_units:
      tax_unit:
        members: [person1, person2]
        premium_tax_credit: 0
    households:
      household:
        members: [person1, person2]
        state_code: TX
  output:
    taxsim_tfica: 4896.00
    income_tax: -660.00
```

Here are the results generated by the `openfisca-us test` command:
```
================================= FAILURES ===================================
_______________________________ test session _________________________________
/Users/mrh/work/m21-id99970.test.yaml:
  Test 'Tax unit with recid 99970 from m21.ita.csv':
    income_tax@2021: [-1660.] differs from -660.0 
      with an absolute margin [1000.] > 0.01
========================= short test summary info ============================
FAILED m21-id99970.test.yaml::
============================== 1 failed in 1.15s ===============================
```

Excerpts from OpenFisca-US trace output:
```
income_tax_before_credits<2021> >> [5140.]
non_refundable_ctc<2021> >> [500.]
american_opportunity_credit<2021> >> [2500.]
lifetime_learning_credit<2021> >> [0.]
income_tax_before_refundable_credits<2021> >> [2140.]
refundable_american_opportunity_credit<2021> >> [1000.]
rrc_arpa<2021> >> [2800.]
income_tax<2021> >> [-1660.]
```

Excerpts from USI-T-A dump output:
```
taxbc 5140.0      <--- income tax liability before credits
odc 500.0
etc_llc_option 0  <--- apply tuition to AOC rather than LLC
c07230 1500.0     <--- non-refundable AOC portion
c10960 1000.0     <--- refundable AOC portion
rrc 2800.0
itax -660.0       <--- income tax liability after credits
```

We know that for a person with qualified tuition expenses, the 2021 AOC credit total (the sum of the refundable and non-refundable portions) can never exceed $2500.  But the OpenFisca-US trace output (excerpted above) shows that the AOC is reducing tax liability by $3500.

It may well be that the basic AOC calculations are all fine, but that there is some small oversight in the logic that splits the total AOC amount into its two portions.   Whatever the problem, this test case has a $1000 income tax difference between OpenFisca-US and USI-Tax-Analyzer.  We are comparing against USI-Tax-Analyzer in this test because TAXSIM35 does not simulate education credits.
