### ISSUE TITLE
Incorrect above-the-line-deduction for qualified tuition expenses before 2021

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#1318]
Before 2021, qualified tuition expenses could be taken as an above-the-line-deduction lowering  AGI.  Turbo Tax believes the amount of tuition expenses that can be used to reduce AGI is limited to $4000 per person with tuition expenses as shown in this screenshot:

<img width="1742" alt="Screen Shot 2022-09-01 at 1 02 01 PM" src="https://user-images.githubusercontent.com/12170745/188014324-c5e61492-c7d8-4d22-bf4e-2ffafdbed5d4.png">

The following simple YAML test file shows that OpenFisca-US 0.129.2 version does not cap the above-the-line-deduction, and therefore, reduces AGI by too much.   Here is test case:
```
- name: Tax unit created by hand for AGI test
  absolute_error_margin: 0.01
  period: 2020
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 25
        ssi: 0
        state_supplement: 0
        wic: 0
        employment_income: 74000
        qualified_tuition_expenses: 14000
        is_eligible_for_american_opportunity_credit: 1
    spm_units:
      spm_unit:
        members: [person1]
        snap: 0
        tanf: 0
    tax_units:
      tax_unit:
        members: [person1]
        premium_tax_credit: 0
    households:
      household:
        members: [person1]
        state_code: TX
  output:
    adjusted_gross_income: 70000
```

Here are the test results for the above case:
```
================================= FAILURES ===================================
_______________________________ test session _________________________________
/Users/mrh/work/m20-id0.test.yaml:
  Test 'Tax unit created by hand for AGI test':
    adjusted_gross_income@2020: [60000.] differs from 70000.0 
      with an absolute margin [10000.] > 0.01
========================= short test summary info ============================
FAILED m20-id0.test.yaml::
============================ 1 failed in 0.49s ===============================
```

And here are some excerpts from the test trace output:
```
irs_gross_income<2020> >> [74000.]
qualified_tuition_expenses<2020> >> [14000.]
above_the_line_deductions<2020> >> [14000.]
adjusted_gross_income<2020> >> [60000.]
```

The USI-Tax-Analyzer generates an AGI amount of $70,000 for this case.  This case cannot be simulated by TAXSIM35 because that model does not have qualified tuition expenses as an input variable.
