### ISSUE TITLE
Missing MA Two-Income Married Couple Subtraction Worksheet logic

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#1481]
When comparing 2021 MA income taxes produced by PolicyEngine-US
0.176.0 versus TAXSIM35 10/24/22 version, we get many differences
for even simple tax units.

One problem is that PolicyEngine is missing logic for the Two-Income
Married Couple Subtraction Worksheet.

Here is the test case showing the difference between the two models
for a married couple with two incomes:
```
# PolicyEngine US test file derived from p21.its.csv and p21.ots.csv files

- name: Tax unit with taxsimid 2074 from p21.its.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 34
        employment_income: 4000
        ssi: 0
        state_supplement: 0
        wic: 0
      person2:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 1
        is_tax_unit_dependent: 0
        age: 40
        employment_income: 20000
        ssi: 0
        state_supplement: 0
        wic: 0
      person3:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 11
        ssi: 0
        state_supplement: 0
        wic: 0
      person4:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 11
        ssi: 0
        state_supplement: 0
        wic: 0
      person5:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 16
        ssi: 0
        state_supplement: 0
        wic: 0
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4, person5]
        snap: 0
        tanf: 0
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4, person5]
        premium_tax_credit: 0
    households:
      household:
        members: [person1, person2, person3, person4, person5]
        state_code: MD
  output:
    md_income_tax: -3308.00

```

The results for the above test case are:
```
================================= FAILURES ===================================
_______________________________ test session _________________________________
/Users/mrh/work/PolicyEngine-US/MD/p21-id2074.test.yaml:
  Test 'Tax unit with taxsimid 2074 from p21.its.csv':
    md_income_tax@2021: [-2871.0999] differs from -3308.0
                        with an absolute margin [436.90015] > 0.01
========================= short test summary info ============================
FAILED p21-id2074.test.yaml::
============================ 1 failed in 0.54s ===============================
```
