### ISSUE TITLE
Incorrect calculation of PA taxable income

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#1484]
When comparing 2021 PA income taxes produced by PolicyEngine-US 0.176.0 versus TAXSIM35 10/24/22 version, we get many differences even for simple tax units.

One problem is that the calculation of taxable income under the PA income tax is not correct.  If we go the the [PA government document](https://www.revenue.pa.gov/FormsandPublications/FormsforIndividuals/PIT/Documents/2021/2021_pa-40in.pdf#page=8) referenced in the `pa_total_taxable_income` variable code, we see this:
<img width="726" alt="Screen Shot 2022-11-06 at 11 27 27 AM" src="https://user-images.githubusercontent.com/12170745/200182615-9a68f5d6-d607-44e4-8d7d-865cebf54d0e.png">

The `pa_total_taxable_income` variable formula sets that variable equal to the US `adjusted_gross_income` variable, which the referenced document shows is not true.  At a minimum, social security benefits, pension benefits, and unemployment benefits are not included in PA taxable income.

Here is a test case showing this difference between the two models:
```
# PolicyEngine US test file derived from q21.its.csv and q21.ots.csv files

- name: Tax unit with taxsimid 2018 from q21.its.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 72
        employment_income: 20000
        social_security: 24000
        real_estate_taxes: 8000
        interest_expense: 10000
        ssi: 0
        state_supplement: 0
        wic: 0
      person2:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 1
        is_tax_unit_dependent: 0
        age: 74
        employment_income: 30000
        ssi: 0
        state_supplement: 0
        wic: 0
      person3:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 11
        ssi: 0
        state_supplement: 0
        wic: 0
      person4:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 11
        ssi: 0
        state_supplement: 0
        wic: 0
      person5:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 16
        ssi: 0
        state_supplement: 0
        wic: 0
      person6:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 16
        ssi: 0
        state_supplement: 0
        wic: 0
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4, person5, person6]
        snap: 0
        tanf: 0
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4, person5, person6]
        premium_tax_credit: 0
        pa_use_tax: 0  # not considered by TAXSIM35 to part of PA income tax
    households:
      household:
        members: [person1, person2, person3, person4, person5, person6]
        state_code: PA
  output:
    pa_income_tax: 0.00
```

The results for the above test case are:
```
================================= FAILURES ===================================
_______________________________ test session _________________________________
/Users/mrh/work/PolicyEngine-US/PA/q21-id2018.test.yaml:
  Test 'Tax unit with taxsimid 2018 from q21.its.csv':
    pa_income_tax@2021: [2161.28] differs from 0.0
                        with an absolute margin [2161.28] > 0.01
========================= short test summary info ============================
FAILED q21-id2018.test.yaml::
============================ 1 failed in 0.44s ===============================
```
