### ISSUE TITLE
MA excess exemption not applied to long-term capital gains

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#1521]
This [Massachusetts government document](https://www.mass.gov/service-details/view-massachusetts-personal-income-tax-exemptions) and the [2021 Form 1](https://www.mass.gov/doc/2021-form-1-massachusetts-resident-income-tax-return/download) and the [Form 1 instructions](https://www.mass.gov/doc/2021-form-1-instructions/download), all make it clear that any excess (or unused) exemption amount can be applied to dividends, and then if there is any remaining excess exemption, the remainder can be applied to short-term capital gains, and then any remaining excess exemption can be applied to long-term capital gains.

PolicyEngineUS is not taking that last step to reduce taxable long-term capital gains by any remaining excess exemption.

Here is a case illustrates the problem:
```
- name: Tax unit with taxsimid 86195 in t21.its.csv and t21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 27
        employment_income: 1000
        taxable_interest_income: 2010
        short_term_capital_gains: 2010
        long_term_capital_gains: 10010
        social_security: 22000
        rent: 17000
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1]
        premium_tax_credit: 0  # not in TAXSIM35
    households:
      household:
        members: [person1]
        state_code: MA
  output:  # expected results from MAI-Tax-Analyzer (given TAXSIM35 bug)
    ma_income_tax: 381.00
    #
    # For info on the MA Income Tax Analyzer, browse the following URL:
    # https://chiselapp.com/user/PSG/repository/Tax-Analyzer-Framework/
    # TAXSIM35 10/24/22 version generates for this case a MA income tax
    # of zero, which is clearly incorrect.
    #
    # DETAILS:
    # Deductions reduce PartB taxable income (on wages and interest) to
    # zero, leaving the $4400 personal exemption completely unused.
    # Under MA law, the unused (or excess) exemption if first used
    # to reduce the $2010 in PartA STCG to zero.  But that leaves a
    # $2390 unused exemption, which can then be used to reduce the
    # $10,010 in LTCG to $7620 in PartC taxable income.  The flat PartC
    # tax rate is 5.00% in 2021, so the MA income tax amount for this case
    # is $381.  It is this last reduction that is missing in PolicyEngineUS.
    #
    # REFERENCE:
    # That an unused (or excess) PartB exemption can be used to reduce BOTH
    # PartA and PartC income is described in the document at this URL:
    # https://www.mass.gov/service-details/view-massachusetts-personal-income-tax-exemption
```

Here are test results for the above case:
```
================================= FAILURES ===================================
_______________________________ test session _________________________________
/Users/mrh/work/Policy-Engine-US/MA/t21-id86195.yaml:
  Test 'Tax unit with taxsimid 86195 in t21.its.csv and t21.ots.csv':
    ma_income_tax@2021: [500.5] differs from 381.0
                        with an absolute margin [119.5] > 0.01
========================= short test summary info ============================
FAILED t21-id86195.yaml::
============================ 1 failed in 0.39s ===============================
```
