### ISSUE TITLE
Presence of a complex reform causes US income tax inaccuracies

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#1539]
One of the guiding principles of the PolicyEngine-US project is to avoid adding complex reforms to the code base.  Including complex reforms makes the code more complicated, and hence, more difficult to maintain.  The preferred approach is to use the [powerful capability for specifying complex reforms](https://openfisca.org/doc/coding-the-legislation/reforms.html) that is part of the PolicyEngine-Core framework.  This approach keeps legislative reforms (which come and go) separate from the code base that describes legislative history.

The validation testing against TAXSIM35 using the c21 sample that is described in issue #1538, highlights the pitfalls of including complex reforms in the code base.  The c21 sample has more than 90% of its tax units having a difference with TAXSIM35, with the differences being as large as one thousand dollars.   The complex reform included in the code base that causes all these differences involves parameters and code to allow reforms that tax pass-through income using different tax bracket rates and thresholds.

The following simple test case illustrates these tax differences:
```
- name: Single taxpayer with both wage and self-employment income
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: 1
        age: 50
        employment_income: 90_000
        self_employment_income: 100_000
        business_is_qualified: false
        business_is_sstb: false
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1]
        premium_tax_credit: 0  # not in TAXSIM35
    households:
      household:
        members: [person1]
        state_code: TX  # no state income tax
  output:  # expected results from online TAXSIM35 12/02/22 version
    taxsim_tfica: 16_110.35
    adjusted_gross_income: 185_387.33
    taxable_income: 172_837.33
    income_tax: 36_134.94
```
Here are the test results for this case:
```
================================= FAILURES ===================================
_______________________________ test session _________________________________
/Users/mrh/work/Policy-Engine-US/US/pt-bug.yaml:
  Test 'Single taxpayer with both wage and self-employment income':
    income_tax@2021: [36514.445] differs from 36134.94140625
                     with an absolute margin [379.5039] > 0.01
========================= short test summary info ============================
FAILED pt-bug.yaml::
============================ 1 failed in 0.92s ===============================
```
