### ISSUE TITLE
Add missing OR retirement credit

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#1674]
The 0.200.5 version does not include the non-refundable Oregon retirement credit.  This credit has been a feature of the Oregon income tax for years, so it must be described in the legislation.

The absence of this credit means that many elderly with modest incomes have their Oregon income tax liability overstated by a substantial amount.   The following integration test illustrates this problem:

```
- name: Elderly OR couple with modest pension, social security, and bond income
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: true
        age: 67
        taxable_interest_income: 9000.0
        taxable_pension_income: 5000.0
        social_security: 1000.0
      person2:
        is_tax_unit_spouse: true
        age: 67
        taxable_interest_income: 9000.0
        taxable_pension_income: 5000.0
        social_security: 1000.0
    tax_units:
      tax_unit:
        members: [person1, person2]
        premium_tax_credit: 0
    households:
      household:
        members: [person1, person2]
        state_code: OR
  output:
    or_income_tax_before_credits: 1349.75
    or_exemption_credit: 426.00
    # or_retirement_credit: 900.00  # variable not defined in PolicyEngineUS
    or_income_tax: 23.75  # = 1349.75 - 426.00 - 900.00
```
