### ISSUE TITLE
Fix inaccurate NY supplemental tax calculations

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#1679]
In some cases, the 0.200.6 version of PolicyEngineUS produces incorrect 2021 values for the `ny_supplemental_tax` variable, and therefore, incorrect 2021 values for the `ny_income_tax` variable.

Currently there are no unit tests for the `ny_supplemental_tax` variable formula.
Below I show two units tests: the first of which passes and the second of which fails.

```
- name: Unit test 1 for ny_supplemental_tax
  absolute_error_margin: 0.01
  period: 2021
  input:
    state_code: NY
    filing_status: JOINT
    ny_agi: 256_000
    ny_taxable_income: 238_950
    ny_main_income_tax: 14_069.755
  output:
    ny_supplemental_tax: 1_055.78
    # calculated by hand using input and worksheet 2 on page 52 of the
    # 2021 NY Form IT-201 Instructions, which is at the following URL:
    # https://www.tax.ny.gov/pdf/2021/inc/it201i_2021.pdf#page=52

- name: Unit test 2 for ny_supplemental_tax
  absolute_error_margin: 0.01
  period: 2021
  input:
    state_code: NY
    filing_status: JOINT
    ny_agi: 324_030
    ny_taxable_income: 307_980
    ny_main_income_tax: 18_439.35
  output:
    ny_supplemental_tax: 1_055.78
    # calculated by hand using input and worksheet 2 on page 52 of the
    # 2021 NY Form IT-201 Instructions, which is at the following URL:
    # https://www.tax.ny.gov/pdf/2021/inc/it201i_2021.pdf#page=52
```

The second unit test fails with an output difference of $1,038.25.
