### ISSUE TITLE
Incorrect IL income additions

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#1683]
The variable `il_base_income_additions` produces too large an amount in some cases.  The formula for this variable is:
```
adds = "gov.states.il.tax.income.base.additions"
```
And the parameter `additions` list is defined as follows:
```
description: Illinois Base Income Addition Sources
values:
  2021-01-01:
    - tax_exempt_interest_income
    - dividend_income
    - il_schedule_m_additions
metadata:
  unit: variable
  name: il_base_income_additions
  label: IL Base Income Additions
  reference:
    - title: Illinois Income Tax Act, 35 ILCS 5/502 (from Ch. 120, par. 5-502) Sec. 502. Returns and notices.
      href: https://www.ilga.gov/legislation/ilcs/ilcs5.asp?ActID=577&ChapterID=8
    - title: Illinois Department of Revenue 2021 Schedule M IL-1040 Instructions
      href: https://www2.illinois.gov/rev/forms/incometax/Documents/currentyear/individual/IL-1040-Schedule-M-Instr.pdf
```
Why are `tax_exempt_interest_income` and `divident_income` on that list of additions?  Here is what the second cited `href` says:

<img width="767" alt="Screenshot 2023-01-19 at 10 51 46 AM" src="https://user-images.githubusercontent.com/12170745/213495395-33f5d0e0-4890-48df-958b-05615216f90d.png">

So, it seems as if the inclusion of `tax_exempt_interest_income` and `dividend_income` as additions is based on a misreading of the instructions for Step 2, Line 1.   The instructions make it clear that these additions are **only** for income "earned by your child if you elected to report your child’s interest and dividend income on federal Form 8814."

As a result of this mistaken inclusion of `tax_exempt_interest_income` and `dividend_income` in the additions list, when that kind of income is earned by the tax unit's head or spouse, then IL taxable income will be overstated, and hence, IL income tax liability will be overstated.  Essentially these kinds of income are being double counted in IL taxable income.

This double counting has arisen in testing IL income tax results against TAXSIM35 results.

As PolicyEngineUS has no characterization of "federal Form 8814", the way to solve this problem is to remove the `tax_exempt_interest_income` and `dividend_income` variables from the `parameters/gov/states/il/tax/income/base/additions.yaml` list.
