### ISSUE TITLE
Incorrect 2022 non-refundable CTC calculations

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#1707]
Using the 0.203.8 version to simulate 2022 federal income taxes, I find puzzling CTC amounts in some cases.   These problems were found by comparing PolicyEngineUS income tax amounts with those generated by TAXSIM35 (as patched on 2023-01-26).   Here is an integration test (in which TAXSIM35 results are used to specify the expected PolicyEngineUS output):
```
- name: Tax unit with taxsimid 4690 in x22.its.csv and x22.ots.csv
  absolute_error_margin: 0.01
  period: 2022
  input:
    people:
      person1:
        is_tax_unit_head: true
        age: 44
        employment_income: 7_010
        non_qualified_dividend_income: 4_010
        social_security: 18_000
        self_employment_income: 19_010
        business_is_qualified: true
        business_is_sstb: true
        w2_wages_from_qualified_business: 100e6
      person2:
        age: 16
      person3:
        age: 16
      person4:
        age: 16
      person5:
        age: 17
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4, person5]
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4, person5]
        premium_tax_credit: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2, person3, person4, person5]
        state_code: TX  # no state income tax
  output:  # expected results from patched TAXSIM35 2023-01-26 version
    taxsim_tfica: 3_222.29
    income_tax_before_credits: 1_353.67
    non_refundable_ctc: 1_353.67  # PEUS generates 2_972.00
    refundable_ctc: 3_326.55  $ PEUS generates 3_528.00 for the ACTC
    income_tax: -6_851.74  # PEUS 0.203.8 version generates -7_053.19
```

Note that the two models agree on the value of `income_tax_before_credits`, but disagree on the `non_refundable_ctc` and `refundable_ctc` amounts.

The most troubling aspect of the PolicyEngineUS output is that the value of the `non_refundable_ctc` variable is larger than the value of the `income_tax_before_credits` variable.  That does not seem to be correct given that the CTC was a non-refundable credit in 2022.

I'm not fully convinced that the current version of TAXSIM35 handles the above integration test case correctly in all respects, but at least it limits the non-refundable CTC to the pre-credits tax liability.

If the `non_refundable_ctc` variable is supposed to represent the non-refundable CTC, then it does appear as if there is a bug in the PolicyEngineUS CTC logic.  This bug did not appear in 2021 testing because the child tax credit was fully refundable in that year.
