### ISSUE TITLE
MA tax legislation regarding US ALDs

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#1739]
When looking at the [2021 MA Form 1 Schedule C](https://www.mass.gov/doc/2021-schedule-c-massachusetts-profit-or-loss-from-business/download) there appears to be no provision for subtracting from MA net self-employment income the US `self_employment_tax_ald` amount.   Yet the PolicyEngineUS code allows that subtraction citing this MA legislation:
```
description: Above-the-line deductions disallowed in Massachusetts income tax.
values:
  2001-01-01:
    - loss_ald # (c)
    - ira_contributions # (f)
    - sep_simple_qualified_plan_contributions # (f)
    - early_withdrawal_penalty # (h)
metadata:
  unit: variable
  name: ma_ald_disallowed
  label: MA Above-the-line deductions disallowed
  reference:
    - title: Mass. General Laws c.62 § 2(d)(1)(A)
      href: https://www.mass.gov/info-details/mass-general-laws-c62-ss-2
```
But when I look at § 2(d)(1)(A), all I see is this:

<img width="1140" alt="Screenshot 2023-02-01 at 1 29 03 PM" src="https://user-images.githubusercontent.com/12170745/216130849-7abc79aa-d6d4-4202-a76b-5bfec2462569.png">

This text does not seem to address the status of the US SECA ALD under MA law.
It seems to be talking about "deductions allowed to life tenants and income beneficiaries" under the US tax law.  What does that have to do with SECA taxes?

Given that the Schedule C form seems to disallow the subtraction of the US SECA ALD, why exactly is the `self_employment_tax_ald` variable **not** in the list of disallowed US ALDs in the [disallowed.yaml](https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/parameters/gov/states/ma/tax/income/ald/disallowed.yaml) parameter file?
