### ISSUE TITLE
Incorrect MD AGI subtraction for child/dependent care expenses

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#1746]
In PR #1648 I corrected problems with the `md_dependent_care_subtraction` formula, but I made a mistake in the new code.  That PR included an integration test of the new formula code, but that test did not detect the mistake.  The mistake has now been identified in the process of comparing results from PolicyEngineUS with TAXSIM35 in a sample of 100,000 randomly-generated MD income tax integration tests (see the MD `g21` sample results in issue #993).

The following simplified integration test illustrates the mistake.
```
- name: MD integration test checking 2021 AGI subtractions
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: true
        age: 32
        employment_income: 20_000
        taxable_interest_income: 12_000
        taxable_pension_income: 52_000
        social_security: 15_000
      person2:
        age: 11
      person3:
        age: 10
      person4:
        age: 9
      person5:
        age: 8
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4, person5]
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4, person5]
        tax_unit_childcare_expenses: 10_000
    households:
      household:
        members: [person1, person2, person3, person4, person5]
        state_code: MD
  output:
    tax_unit_taxable_social_security: 12_750
    adjusted_gross_income: 72_000 + 12_000 + 12_750  # = 96_750
    md_socsec_subtraction: 12_750
    md_two_income_subtraction: 0
    md_dependent_care_subtraction: 2 * 3_000  # = 6_000
```

With the current code, this test fails because PolicyEngineUS generates 10_000 as the value of the `md_dependent_care_subtraction` variable.
