### ISSUE TITLE
Incorrect MD itemized deduction calculations

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#1764]
When I fill out the [2021 MD Form 502](https://www.marylandtaxes.gov/forms/21_forms/502.pdf#page=2), following the [instructions](https://www.marylandtaxes.gov/forms/21_forms/Resident_Booklet.pdf#page=18), for the very simple tax unit specified in the integration test below, I find that PolicyEngineUS 0.213.3 version does not generate the correct itemized deduction amount.  And, as a result, the MD taxable income and MD income tax amounts are incorrect.  Here is the test case:
```
- name: 2021 MD integration test for a single coupon-clipping homeowner
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: true
        age: 40
        taxable_interest_income: 200_000
        real_estate_taxes: 12_000
        interest_expense: 24_000
    spm_units:
      spm_unit:
        members: [person1]
    tax_units:
      tax_unit:
        members: [person1]
        premium_tax_credit: 0
    households:
      household:
        members: [person1]
        state_code: MD
  output:  # expected results from hand calculations using 2021 MD Form 502
    md_agi: 200_000
    md_deductions: 34_000  # PEUS 0.213.3 code generates 24_000
    md_taxable_income: 200_000 - 34_000  # code generates 200_000 - 24_000
```
And here are the test results:
```
================================= FAILURES ===================================
_______________________________ test session _________________________________
  Test '2021 MD integration test for a single coupon-clipping homeowner':
    md_deductions@2021: [24000.] differs from 34000.0 
                        with an absolute margin [10000.] > 0.01
========================= short test summary info ============================
FAILED itemded.yaml::
============================ 1 failed in 0.83s ===============================
```

Am I filling out the Form 502 incorrectly?  If not, there seems to be a bug in PolicyEngineUS.
