### ISSUE TITLE
MO social security deduction calculations are still incorrect

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#1787]
Following the merge of PR #1780, the MO section C calculations are still incorrect.  Here is a test case where the MO tax unit has an AGI of roughly $100,000 but has a taxable income of zero.

```
- name: Tax unit with taxsimid 77665 in f21.its.csv and f21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: true
        age: 41
        employment_income: 18_010
        taxable_interest_income: 5_505
        taxable_pension_income: 500
        social_security: 9_000
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person2:
        is_tax_unit_spouse: true
        age: 41
        employment_income: 57_010
        taxable_interest_income: 5_505
        taxable_pension_income: 500
        social_security: 9_000
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person3:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person4:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person5:
        age: 16
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person6:
        age: 16
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4, person5, person6]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4, person5, person6]
        premium_tax_credit: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2, person3, person4, person5, person6]
        state_code: MO
  output:  # expected results from patched TAXSIM35 2023-02-13 version
    mo_income_tax: 3095.77
```
The test results are:
```
================================= FAILURES ===================================
_______________________________ test session _________________________________
/Users/mrh/work/Policy-Engine-US/MO/f21-id77665.yaml:
  Test 'Tax unit with taxsimid 77665 in f21.its.csv and f21.ots.csv':
    mo_income_tax@2021: [0.] differs from 3095.77001953125
                       with an absolute margin [3095.77] > 0.01
========================= short test summary info ============================
FAILED f21-id77665.yaml::
============================== 1 failed in 0.69s ===============================
```
