### ISSUE TITLE
Incorrect MO section B pension deduction calculations

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#1791]
The MO section B pension deduction calculations are not quite right.  This was revealed by filing out the [2021 MO Form 1040 Part 3 Section B](https://dor.mo.gov/forms/MO-1040%20Fillable%20Calculating_2021.pdf#page=9) by hand for a test case that was generated as part of the validation testing against TAXSIM35.  Here is the test case:
```
- name: Tax unit with taxsimid 94115 in f21.its.csv and f21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: true
        age: 69
        employment_income: 15_010
        taxable_interest_income: 5_505
        taxable_pension_income: 3_000
        social_security: 1_500
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person2:
        is_tax_unit_spouse: true
        age: 69
        employment_income: 3_010
        taxable_interest_income: 5_505
        taxable_pension_income: 3_000
        social_security: 1_500
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person3:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2, person3]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2, person3]
        premium_tax_credit: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2, person3]
        state_code: MO
  output:  # expected results from hand calculations using 2021 MO Form 1040
    mo_pension_and_ss_or_ssd_deduction_section_b: [1_485, 1_485, 0]
    mo_pension_and_ss_or_ssd_deduction_section_c: [750, 750, 0]
```
The results for this test were correct for section C deductions, but not for section B deductions because the code generated zero section B deductions.
