### ISSUE TITLE
Decouple California CDCC calculation from ARPA in 2021

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#2060]
The recent merge of pull request #2043 did not resolve issue #1913.
The 2021 test case included in issue #1913 still has an incorrect `ca_cdcc` amount.

In this issue I examine a different test case (see below) and hand calculate the `ca_cdcc` amount using the 2021 form and instructions cited in issue #1913.   PolicyEngineUS generates a `ca_cdcc` value of $1700 for this test case.  The hand calculations produce $408, which is the same value as generated for this case by the patched version of TAXSIM35 described in issue #933.

This large $1292 difference in the value of `ca_cdcc` is caused by the fact that PolicyEngineUS does not recognize that California has decoupled its CDCC from the federal CDCC (just as it has decouple CalEITC from the federal EITC).

After showing the test case and its test results, I explain the hand calculations required by the form and its instructions.

Here is the integration test case:
```
- name: Tax unit with taxsimid 37810 in g21.its.csv and g21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: true
        age: 58
        employment_income: 74_010
        taxable_interest_income: 11_010
        taxable_private_pension_income: 10_000
        social_security: 2_000
        rent: 9_000
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person2:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person3:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person4:
        age: 16
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4]
        tax_unit_childcare_expenses: 10_000
        premium_tax_credit: 0  # not in TAXSIM35
        ca_use_tax: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2, person3, person4]
        state_code: CA
  output:  # expected results from patched TAXSIM35 2023-03-28 version
    ca_cdcc: 408
```

And here are the test results (using the 0.263.2 version):
```
================================= FAILURES ===================================
_______________________________ test session _________________________________
/Users/mrh/work/Policy-Engine-US/CA/g21-id37810.yaml:
  Test 'Tax unit with taxsimid 37810 in g21.its.csv and g21.ots.csv':
    ca_cdcc@2021: [1700.] differs from 408.0 with an absolute margin [1292.] > 0.01
```

Here is an explanation of filling out 2021 Form 3506 by following its instructions:

- Form line 3 is $6000  (not the actual expenses of $10,000)
- Form line 6 is $6000  (because the single parent's wages are greater than $6000)
- Form line 7 is 0.20  (because federal AGI is greater than $43,000)
- Form line 8 is $1200  (that is, 0.20 times $6000)
- Form line 9 is 0.34  (because federal AGI is between $70,000 and $100,000)
- Form line 10 is $408  (that is, 0.34 times $1200)

So, in the current version of PolicyEngineUS, there are missing CA CDCC parameters (which are on the forms and in their instructions) and missing `ca_cdcc` formula logic that uses the CA parameters in the way the forms and their instructions indicate.
