### ISSUE TITLE
Add 2021 Utah retirement credit and taxpayer credit parameters

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#2180]
The Utah state income tax code has several problems.  The integration test presented below illustrates two of those problems.   

**First**, the taxpayer credit is incorrect because PolicyEngineUS projects the 2022 phase-out threshold value (which is correct) back to 2021.   This is happening even though earlier in the development of the Utah income tax the 2021 parameter values were in the code.  This can be seen in the following screenshot of a March 23rd code review session for pull request #1994.

<img width="1089" alt="Screenshot 2023-04-25 at 9 48 15 AM" src="https://user-images.githubusercontent.com/12170745/234327463-2619e70d-acdf-4117-a12c-1e7773820f06.png">

When #1994 was merged a month later, the 2021 values had been removed.  This is just one example of the many missing 2021 parameter values.  The 2021 parameter values are **missing** because some Utah tax parameters are specified as far back as 2020, 2018, and even 2008.

**Second**, the retirement credit is incorrect.  PolicyEngineUS generates a retirement credit for this test case that is zero when following the TC-40 form instructions produces a value of $624.50.  The $624.50 retirement credit is also generated by TAXSIM35.

Here is the integration test case followed by the test results:
```
- name: Tax unit with taxsimid 95281 in p21.its.csv and p21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: true
        age: 73
        employment_income: 21_010
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person2:
        is_tax_unit_spouse: true
        age: 73
        employment_income: 22_010
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2]
        premium_tax_credit: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2]
        state_code: UT
  output:  # expected results from patched TAXSIM35 2023-04-24 version
    ut_income_tax: 3.78
```
This test case produces these results:
```
  Test 'Tax unit with taxsimid 95281 in p21.its.csv and p21.ots.csv':
    ut_income_tax@2021: [616.50195] differs from 3.7799999713897705 
                        with an absolute margin [612.7219] > 0.01
```
