### ISSUE TITLE
Remove the {short,long}_term_capital_losses variables

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#2622]
There are four person-level income variables related to capital gains:
* `short_term_capital_gains`
* `short_term_capital_losses`
* `long_term_capital_gains`
* `long_term_capital_losses`

The documentation of these variables does not make it clear (at least to me) how to use these variables.   I'm assuming that the four variables are all supposed to be non-negative in value and then the code computes net gains (which can be positive or negative).   But that assumption is not correct.  Proceeding under that assumption leads to incorrect AGI results (as shown in the tests below).  Ignoring the capital losses variables and entering a loss as a negative gain does produce correct AGI results.

These tests show that the `{short,long}_capital_losses` variables are redundant and that there existence is dangerous in the sense that using them will produce incorrect results.

Here are the two simple tests, the first of which passes and the second of which fails giving an `adjusted_gross_income` value of 100_000, which is clearly incorrect.

```
- name: capital_losses integration test 1
  absolute_error_margin: 0.01
  period: 2018
  input:
    people:
      person1:
        is_tax_unit_head: true
        age: 40
        employment_income: 100_000
        long_term_capital_gains: -5_000
    tax_units:
      tax_unit:
        members: [person1]
    spm_units:
      spm_unit:
        members: [person1]
    households:
      household:
        members: [person1]
        state_code: TX  # skip state income tax calculations
  output:
    adjusted_gross_income: 97_000

- name: capital_losses integration test 2
  absolute_error_margin: 0.01
  period: 2018
  input:
    people:
      person1:
        is_tax_unit_head: true
        age: 40
        employment_income: 100_000
        long_term_capital_losses: 5_000
    tax_units:
      tax_unit:
        members: [person1]
    spm_units:
      spm_unit:
        members: [person1]
    households:
      household:
        members: [person1]
        state_code: TX  # skip state income tax calculations
  output:
    adjusted_gross_income: 97_000
```
