### ISSUE TITLE
New Mexico income tax integration test failure

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#2729]
@PavelMakarchuk,  When you asked me to test the newly developed NM income tax module, you said you wanted to be involved in the process.  So, here is your chance.

The newest results in issue #993 show that there are many NM differences in the simplest `p21` sample between PolicyEngine-US 0.396.0 and the latest patched version of TAXSIM35.  Below is a test case from that `p21` sample.  So, now we are at step 6 in the process described in topic #2389: the two models produce different results, but it isn't clear which model is wrong.

Use the methods described in step 6 to answer that question.

Here are the results from running the test:
```
  Test 'Tax unit with taxsimid 86990 in p21.its.csv and p21.ots.csv':
    nm_income_tax@2021: [-250.] differs from -941.010009765625
                        with an absolute margin [691.01] > 0.01
```
And here is the YAML-formatted test:
```
- name: Tax unit with taxsimid 86990 in p21.its.csv and p21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: true
        age: 66
        employment_income: 1010
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person2:
        is_tax_unit_spouse: true
        age: 66
        employment_income: 8010
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2]
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
        nm_2021_income_rebate: 0  # not in TAXSIM35
        nm_additional_2021_income_rebate: 0  # not in TAXSIM35
        nm_supplemental_2021_income_rebate: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2]
        state_code: NM
  output:  # expected results from patched TAXSIM35 2023-07-27 version
    nm_income_tax_before_refundable_credits: 0.00
    nm_income_tax: -941.01
```
