### ISSUE TITLE
Add use of New Mexico dependent deductions

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#2737]
The integration test below shows that even though there is code that calculates the NM deduction for certain dependents, that variable is not used in the `nm_deductions` formula.

Here is the integration test, which is followed by the test results using the 0.401.1 version.

```
- name: Tax unit with taxsimid 99570 in p21.its.csv and p21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: true
        age: 53
        employment_income: 120_010
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person2:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person3:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person4:
        age: 16
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person5:
        age: 16
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4, person5]
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
        nm_2021_income_rebate: 0  # not in TAXSIM35
        nm_additional_2021_income_rebate: 0  # not in TAXSIM35
        nm_supplemental_2021_income_rebate: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4, person5]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2, person3, person4, person5]
        state_code: NM
  output:  # expected results from patched TAXSIM35 2023-07-27 version
    nm_agi: 120_010
    nm_taxable_income: 89_210

```

```
  Test 'Tax unit with taxsimid 99570 in p21.its.csv and p21.ots.csv':
    nm_taxable_income@2021: [101210.] differs from 89210.0
                            with an absolute margin [12000.] > 0.01
```
