### ISSUE TITLE
New Mexico CDCC formula is incorrect and not based on unit childcare expenses

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#2756]
The following integration test results show that the NM CDCC logic in PolicyEngine-US needs to be fixed.  The law and the forms make it clear that a tax unit's NM CDCC amount can never be more than $1,2000.  Yet the 0.403.2 code produces a $5,000 amount for this test case.

```
- name: Tax unit with taxsimid 75800 in g21.its.csv and g21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: true
        age: 48
        employment_income: 15_010
        taxable_interest_income: 11_010
        taxable_private_pension_income: 3_000
        social_security: 1_000
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person2:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person3:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person4:
        age: 16
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4]
        tax_unit_childcare_expenses: 10_000
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
        nm_2021_income_rebate: 0  # not in TAXSIM35
        nm_additional_2021_income_rebate: 0  # not in TAXSIM35
        nm_supplemental_2021_income_rebate: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2, person3, person4]
        state_code: NM
  output:  # expected results from patched TAXSIM35 2023-08-01 version
    nm_income_tax_before_refundable_credits: 0.00
    nm_low_income_comprehensive_tax_rebate: 100.00
    nm_cdcc: 0.00
    nm_income_tax: -100.00

# TEST RESULTS USING 0.403.2 CODE:
# Test 'Tax unit with taxsimid 75800 in g21.its.csv and g21.ots.csv':
#    nm_cdcc@2021: [5000.] differs from 0.0
#                  with an absolute margin [5000.] > 0.01
```
