### ISSUE TITLE
Correct Oklahoma itemized deduction logic

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#2777]
Oklahoma is one of the states that requires a taxpayer to use its federal itemization choice when filing their state income tax return.  This rule was not correctly implemented in the original code.   Here is a test case that illustrates the bug:

```
- name: Tax unit with taxsimid 93088 in q21.its.csv and q21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: true
        age: 51
        employment_income: 145_010
        social_security: 15_000
        interest_expense: 6_000
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1]
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
        ok_use_tax: 0  # not in TAXSIM35
        tax_unit_itemizes: True  # on federal return
    spm_units:
      spm_unit:
        members: [person1]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1]
        state_code: OK
  output:  # expected results from patched TAXSIM35 2023-08-05 version
    ok_agi: 145_010  # social security benefits not in OK AGI
    ok_exemptions: 1_000
    ok_taxable_income: 145_010 - 1_000 - 6_000  # must use OK itemized deductions

# TEST RESULTS USING PolicyEngine-US 0.409.0 version:
#   Test 'Tax unit with taxsimid 93088 in q21.its.csv and q21.ots.csv':
#     ok_taxable_income@2021: [137660.] differs from 138010.0
#                             with an absolute margin [350.] > 0.01
```
