### ISSUE TITLE
Colorado integration test failure

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#2931]
Using the 0.450.0 version, the Colorado `e21` sample of 100,000 simple integration tests all pass, but many in the `f21` sample fail.  See issue #993 for a description of these two samples.

An example of the test failures is presented below.  The question is which model is wrong.
TAXSIM35 thinks that all the 2021 federally taxable social security benefits ($20,400) are a Colorado subtraction, while PolicyEngine-US does not.  Here is a [Colorado government description](https://tax.colorado.gov/retirees) that seems helpful.

The following test case generates this error:
```
  Test 'Tax unit with taxsimid 98679 in f21.its.csv and f21.ots.csv':
    co_taxable_income@2021: [58630.] differs from 38230.0
                            with an absolute margin [20400.] > 0.01
```

```
- name: Tax unit with taxsimid 98679 in f21.its.csv and f21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: true
        age: 66
        employment_income: 29_010
        taxable_interest_income: 5_505
        taxable_private_pension_income: 3_500
        social_security: 12_000
      person2:
        is_tax_unit_spouse: true
        age: 66
        employment_income: 26_010
        taxable_interest_income: 5_505
        taxable_private_pension_income: 3_500
        social_security: 12_000
    tax_units:
      tax_unit:
        members: [person1, person2]
        premium_tax_credit: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2]
    households:
      household:
        members: [person1, person2]
        state_code: CO
  output:  # expected results from patched TAXSIM35 2023-08-31 version
    co_taxable_income: 38230.00
    co_income_tax: 1608.35
```
