### ISSUE TITLE
Incorrect Colorado CDCC calculations

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#2937]
The 0.452.0 version has what appears to be a bug in the calculation of the `co_low_income_cdcc` variable.  The instructions for DR-0347 make it clear that the a taxpayer gets **either** the `co_cdcc` amount **or** the `co_low_income_cdcc` amount, **not both**.

Here is a simple test that fails because taxpayers are being given two CDCC refunds:

```
- name: Colorado CDCC test 1
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: true
        age: 41
        employment_income: 12_000
      person2:
        age: 11
    tax_units:
      tax_unit:
        members: [person1, person2]
        tax_unit_childcare_expenses: 9_000
    households:
      household:
        members: [person1, person2]
        state_code: CO
  output:  # expected results from hand calculations using 2021 DR-0347 form
    adjusted_gross_income: 12_000
    cdcc: 4_000
    co_cdcc: 2_000
    co_low_income_cdcc: 0
    # test fails because 0.452.0 code generates $500 for co_low_income_cdcc
```
