### ISSUE TITLE
Incorrect marginal_tax_rate calculation

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3017]
The `marginal_tax_rate` variable is untested in the 0.466.1 version of the model.  When adding the following test, the calculated `marginal_tax_rate` is over 8,000 percent (instead of the expected 43.45 percent). 

```
- name: household_net_income test TX-netinc-base
  absolute_error_margin: 0.01
  period: 2021
  input:
    age: 40
    employment_income: 100_000
    taxable_interest_income: 100_000
    state_fips: 48  # TX
  output:
    household_net_income: 151_539.00

- name: household_net_income test TX-netinc-alt
  absolute_error_margin: 0.01
  period: 2021
  input:
    age: 40
    employment_income: 101_000
    taxable_interest_income: 100_000
    state_fips: 48  # TX
  output:
    household_net_income: 152_104.50

- name: marginal_tax_rate test TX-mtr
  absolute_error_margin: 0.0001
  period: 2021
  input:
    age: 40
    employment_income: 100_000
    taxable_interest_income: 100_000
    state_fips: 48  # TX
  output:  # as expected from above two test results; also same as TAXSIM35
    marginal_tax_rate: 0.4345  # that is, 43.45%
    # using PEUS 0.466.1, marginal_tax_rate is 80.33411, which is ~8033%
    #
    # Test 'marginal_tax_rate test TX-mtr':
    # marginal_tax_rate@2021: [80.33411] differs from 0.4345000088214874
    #                         with an absolute margin [79.899605] > 0.0001
```
