### ISSUE TITLE
Add California alternative minimum tax (AMT)

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3273]
The CA income tax module does not calculate the CA AMT, and therefore, underestimates the state income tax liability of some filers.  TAXSIM35 does calculate a CA AMT amount, but there is no way to check the accuracy of those calculations without Policyengine-US including CA AMT calculations.

The CA AMT amount is calculated on the [Schedule P (540)](https://www.ftb.ca.gov/forms/2021/2021-540-p.pdf) and entered on Line 61 of [Form 540](https://www.ftb.ca.gov/forms/2021/2021-540.pdf#page=3), right above the Mental Health Services Tax, which is included in Policyengine-US.

Below is a test case for which the two models agree on except for TAXSIM35 calculating a $909.63 CA AMT amount, which causes a total CA income tax difference of $909.63.

```
- name: Tax unit with taxsimid 22380 in k21.its.csv and k21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 67
        employment_income: 18010
        qualified_dividend_income: 9010
        taxable_interest_income: 11010
        short_term_capital_gains: 10010
        rental_income: 1010
        taxable_private_pension_income: 2000
        social_security_retirement: 12000
        real_estate_taxes: 24000
        mortgage_interest: 3000
        self_employment_income: 51010
        business_is_qualified: true
        business_is_sstb: true
        w2_wages_from_qualified_business: 100e6
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person2:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person3:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person4:
        age: 16
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person5:
        age: 16
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4, person5]
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
        ca_use_tax: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4, person5]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2, person3, person4, person5]
        state_fips: 6  # CA
  output:  # expected results from patched TAXSIM35 2023-11-16 version
    ca_income_tax: 1146.34
```
