### ISSUE TITLE
Fix Hawaii disabled exemption formula

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3350]
In the 0.552.0 version of Policyengine-US, the Hawaii disabled exemption amount is incorrectly calculated.   The following simple test case illustrates the problem:
```
- name: Hawaii disabled exemption bug
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 30
        employment_income: 48_000
    tax_units:
      tax_unit:
        members: [person1]
    households:
      household:
        members: [person1]
        state_fips: 15  # HI
  output:  # expected results from hand-calculation with N-15 form/instructions
    hi_regular_exemptions: 1_144
    hi_disabled_exemptions: 0     # actual output is 2_288
    hi_exemptions: 1_144          # actual output is 2_288
```
This test case produces the following results:
```
  Test 'Hawaii disabled exemption bug':
    hi_disabled_exemptions@2021: [2288.] differs from 0.0
              with an absolute margin [2288.] > 0.01
```
