### ISSUE TITLE
Fix 2021 South Caroline tax bracket parameters

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3354]
The 0.552.1 version calculates incorrect 2021 SC income tax amounts.  That this is so can be attributed to the fact that there are no units tests to check these 2021 calculations.

The following unit test shows the large magnitude of the 2021 errors:
```
- name: 2021 SC tax bracket bug
  absolute_error_margin: 0.25
  period: 2021
  input:
    sc_taxable_income: 300_000
    state_fips: 45  # SC
  output:  # expected results from hand-calculation specified in 2021 booklet (p.37)
    sc_income_tax: 0.07 * 300_000 - 529
```
Executing this test produces the following results:
```
  Test '2021 SC tax bracket bug':
     sc_income_tax 18842.6 differs from 20471.0
                   with an absolute margin 1628.4
```
