### ISSUE TITLE
Fix South Carolina "senior exemption" calculation

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3394]
Using the 0.564.0 version, the following test fails because PEUS does not correctly offset the `sc_senior_exemption` amount by the `sc_retirement_deduction` amount as called for by the line q-1 and line q-2 worksheets in the [2021 SC income tax instruction booklet](https://dor.sc.gov/forms-site/Forms/IITPacket_2021.pdf#page=18).

```
- name: Tax unit with taxsimid 13715 in f21.its.csv and f21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 67
        employment_income: 27_010
        taxable_interest_income: 5_505
        taxable_private_pension_income: 6_000
        social_security_retirement: 11_500
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person2:
        age: 67
        employment_income: 30_010
        taxable_interest_income: 5_505
        taxable_private_pension_income: 6_000
        social_security_retirement: 11_500
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2]
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2]
        state_fips: 45  # SC
  output:  # expected results from patched TAXSIM35 2023-12-07 version
    sc_retirement_deduction: 12_000
    sc_senior_exemption: 30_000 - 12_000
#
# TEST RESULTS FOR 0.564.0 VERSION:
# Test 'Tax unit with taxsimid 13715 in f21.its.csv and f21.ots.csv':
#   sc_senior_exemption@2021: [30000.] differs from 18000.0
#                             with an absolute margin [12000.] > 0.01
```
