### ISSUE TITLE
Fix Alabama itemized deduction logic

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3505]
The changes in pull request #3495 cause a massive regression in the AL integration test results.
Here is an example of a test case that passed before #3495 but now fails:

```
- name: Tax unit with taxsimid 99120 in e21.its.csv and e21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 32
        employment_income: 155010
        taxable_interest_income: 5505
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person2:
        age: 32
        employment_income: 88010
        taxable_interest_income: 5505
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person3:
        age: 16
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person4:
        age: 16
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person5:
        age: 16
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4, person5]
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4, person5]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2, person3, person4, person5]
        state_fips: 1  # AL
  output:  # expected results from patched TAXSIM35 2023-12-20 version
    al_income_tax: 9670.23
```

Policyengine-US used to generate the same results as TAXSIM35 ($9670.23), but now generates $9119.73.
