### ISSUE TITLE
Fix South Carolina two-wage-earner credit calculation

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3599]
In the 0.615.0 version, the SC two-wage-earner credit calculation does not seem to produce correct results in all cases.   Here is an example:
```
- name: Tax unit with taxsimid 7811 in j21.its.csv and j21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 28
        qualified_dividend_income: 2005
        taxable_interest_income: 5505
        short_term_capital_gains: 4005
        long_term_capital_gains: 1005
        rental_income: 3005
        rent: 24000
        self_employment_income: 21010
        business_is_qualified: true
        business_is_sstb: true
        w2_wages_from_qualified_business: 100e6
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person2:
        age: 28
        employment_income: 108010
        qualified_dividend_income: 2005
        taxable_interest_income: 5505
        short_term_capital_gains: 4005
        long_term_capital_gains: 1005
        rental_income: 3005
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person3:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2, person3]
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2, person3]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2, person3]
        state_fips: 45  # SC
  output:  # expected results from patched TAXSIM35 2024-01-11 version
    sc_income_tax: 8042.25
```
Policyengine-US produces a value of 7895.18, which is $147.07 different from the TAXSIM35 result.   This difference is caused by a $147.07 difference in the two-wage-earner credit:
```
PEUS:    283.75
TAXSIM:  136.68
```
Hand calculation with the form suggests the TAXSIM amount is closer to being correct.
