### ISSUE TITLE
Fix West Virginia senior citizen AGI subtraction logic

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3667]
In the 0.631.0 version, the formula for the `wv_senior_citizen_disability_deduction_person` variable is not correct.   Here is a test case for which the current formula produces a WV taxable income different from that produced by TAXSIM35.

```
- name: Tax unit with taxsimid 88261 in f21.its.csv and f21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 66
        employment_income: 27010
        taxable_interest_income: 5505
        taxable_private_pension_income: 5000
        social_security_retirement: 12000
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person2:
        age: 66
        employment_income: 28010
        taxable_interest_income: 5505
        taxable_private_pension_income: 5000
        social_security_retirement: 12000
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person3:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2, person3]
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2, person3]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2, person3]
        state_fips: 54  # WV
  output:  # expected results from patched TAXSIM35 2024-01-23 version
    wv_income_tax: 2851.05
```
For the above case, the two models produce different `wv_agi` amounts:
```
TAXSIM35          67_170
PEUS              83_170
```
This is a difference of $16,000.
