### ISSUE TITLE
Fix Ohio joint filing credit calculation

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3671]
In the 0.631.0 version, the OH joint filing credit calculation is incorrect.  In the test case presented below, PEUS gives the couple a $269.01 credit while TAXSIM35 gives the couple a zero credit.
TAXSIM35 is giving a zero credit because it thinks this couple in ineligible for the credit because not both the spouses have $500+ in "qualifying income" as defined in 2021 instructions on page 20.  (Hint: the PEUS code mistakenly uses **TAXUNIT** `oh_agi` minus PERSON joint-credit subtractions to compute the joint credit "qualifying income" for each member of the couple.)

```
- name: Tax unit with taxsimid 75376 in e21.its.csv and e21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 26
        taxable_interest_income: 5505
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person2:
        age: 26
        employment_income: 160010
        taxable_interest_income: 5505
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2]
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2]
        state_fips: 39  # OH
  output:  # expected results from patched TAXSIM35 2024-01-11 version
    oh_income_tax: 5380.28
```
