### ISSUE TITLE
Fix Rhode Island property tax credit maximum amount and eligibility criteria

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3704]
In the 0.632.0 version, the RI property tax credit is not always correct.   Consider this case:

```
- name: Tax unit with taxsimid 99988 in g21.its.csv and g21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 71
        employment_income: 2010
        taxable_interest_income: 11010
        taxable_private_pension_income: 6000
        social_security_retirement: 9000
        rent: 17000
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1]
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1]
        state_fips: 44  # RI
  output:  # expected results from patched TAXSIM35 2024-01-26 version
    ri_income_tax: -415.00
```

This test fails because PEUS produces zero for `ri_income_tax` because it thinks the taxpayer is ineligible for the RI property tax credit.   Hand calculations using the 2021 form give the same results as TAXSIM35: a refundable RI property tax credit of $415.
