### ISSUE TITLE
Use `gross_income` rather than `id_agi` in `id_income_tax_liable`

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3709]
In the 0.632.0 version, the requirements for paying the ID PBF $10 tax do not correspond to what the 2021 instructions say.   The instructions say a taxpayer that is not required to file an income tax is not liable for the PBF tax (and there are other reasons a taxpayer would not be PBF liable).   Here are the instruction saying that:

<img width="762" alt="Screenshot 2024-01-27 at 5 17 50 PM" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/a33b5314-8cd3-46db-8694-322535da72bd">

The gross income levels above which taxpayers are required to file an income tax return are as follows:

<img width="1468" alt="Screenshot 2024-01-27 at 5 18 52 PM" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/3af94d56-f108-4f7b-9851-391454686165">

But the code in the `id_pbf_liable` formula does not correspond to these instructions.

As a result of this discrepancy, there are many differences with TAXSIM35.  The following case is an example:

```
- name: Tax unit with taxsimid 99992 in e21.its.csv and e21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 69
        employment_income: 10010
        taxable_interest_income: 11010
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person2:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2]
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2]
        state_fips: 16  # ID
  output:  # expected results from patched TAXSIM35 2024-01-27 version
    id_income_tax: -210.00
```

PEUS fails this test because it calculates the `id_income_tax` amount as -220 dollars, which is the size of the refundable grocery credit for this case.
