### ISSUE TITLE
Add `subtractions.yaml` in `hi_subtractions`, not the `subtractions` folder

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3715]
In the 0.632.0 version, the HI subtractions from federal AGI are not always calculated correctly.
Here is a test that illustrates the problem:

```
- name: Test of hi_subtractions variable
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 62
        employment_income: 115010
        taxable_interest_income: 5505
        taxable_private_pension_income: 6000
        social_security_retirement: 12000
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person2:
        age: 62
        employment_income: 101010
        taxable_interest_income: 5505
        taxable_private_pension_income: 6000
        social_security_retirement: 12000
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person3:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2, person3]
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2, person3]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2, person3]
        state_fips: 15  # HI
  output:  # expected results from filling out the form
    adjusted_gross_income: 259_430
    hi_subtractions: 32_400  
```

This test fails because PEUS produces a zero for the value of the `hi_subtractions` variable.
