### ISSUE TITLE
Use Hawaii AGI in the Hawaii renter credit calculation as opposed to federal AGI

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3733]
In the 0.634.4 version, the HI renter credit is not always calculated correctly.   Here is a test case that illustrates the problem:

```
- name: Tax unit with taxsimid 79840 in g21.its.csv and g21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 73
        employment_income: 1010
        taxable_interest_income: 5505
        taxable_private_pension_income: 4000
        social_security_retirement: 2000
        rent: 9000
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person2:
        age: 73
        employment_income: 10010
        taxable_interest_income: 5505
        taxable_private_pension_income: 4000
        social_security_retirement: 2000
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person3:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person4:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person5:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person6:
        age: 16
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4, person5, person6]
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4, person5, person6]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2, person3, person4, person5, person6]
        state_fips: 15  # HI
  output:  # expected results from patched TAXSIM35 2024-01-29 version
    hi_income_tax: -485.10
```

Policyengine-US fails this test because it produces -85.10 for the `hi_income_tax` amount with the $400 difference being a low-income renter credit of $400 that PEUS is not simulating for this case.
