### ISSUE TITLE
Fix Louisiana federal tax deduction

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3737]
In the 0.636.1 version, the LA federal tax deduction is not always calculated correctly.   It appears as if the `la_federal_tax_deduction` formula is correct (but I have not done a thorough check of whether the PEUS variables used in the formula correspond exactly to the 2021 form line numbers mentioned in the instructions).  Rather, the problem is in the calculation of the 2021 federal non-refundable CTC amount.  I don't understand why roughly a quarter of the tax units in the `e21` sample have negative amounts for the `non_refundable_ctc` variable.   A negative credit amount is a warning sign that something may be amiss in the tax calculations.

Here is a test case that illustrates the problem.   First the test case itself, then some fragments from the test trace.

```
- name: Tax unit with taxsimid 98672 in e21.its.csv and e21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 50
        employment_income: 131_010
        taxable_interest_income: 5_505
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person2:
        age: 50
        employment_income: 157_010
        taxable_interest_income: 5_505
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person3:
        age: 16
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person4:
        age: 16
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person5:
        age: 16
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person6:
        age: 16
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4, person5, person6]
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4, person5, person6]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2, person3, person4, person5, person6]
        state_fips: 22  # LA
  output:  # expected results from patched TAXSIM35 2024-01-30 version
    la_taxable_income: 231_826.42
```

Policyengine-US fails this test because it produces a value of $227,826.42, which is exactly $4,000 less than produced by TAXSIM35.  The reason for this $4K difference can be seen in the trace fragments below:

```
            non_refundable_ctc=                   -4000.00
                income_tax_capped_non_refundable_credits=-4000.00
                income_tax_non_refundable_credits=       -4000.00
            income_tax_before_refundable_credits= 58203.58
```

The negative `non_refundable_ctc` causes the federal income tax before refundable credits to be **larger** than the federal income tax before non-refundable credits.
