### ISSUE TITLE
Fix Rhode Island retirement income subtraction calculation

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3738]
In the 0.636.1 version, the RI retirement income subtraction is not always calculated correctly.  Here is a test case that illustrates the problem:

```
- name: Tax unit with taxsimid 41198 in h21.its.csv and h21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 66
        employment_income: 27_010
        taxable_interest_income: 11_010
        short_term_capital_gains: 10_010
        rental_income: 10_010
        taxable_private_pension_income: 12_000
        social_security_retirement: 22_000
        rent: 5_000
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person2:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person3:
        age: 16
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2, person3]
        tax_unit_childcare_expenses: 6_000
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2, person3]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2, person3]
        state_fips: 44  # RI
  output:  # expected results from patched TAXSIM35 2024-01-30 version
    ri_income_tax: 890.25  # but PEUS calculates 440.25, a difference of $450
    #    The cause of the above tax difference is that ri_taxable_income
    #    differs by $12,000 with TAXSIM35 producing $43,740 and PEUS
    #    producing $31,740.
```
