### ISSUE TITLE
Fix Oregon WFHDC credit calculation

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3743]
In the 0.636.2 version, the OR WFHDC credit is not always calculated correctly.  Specifically, the values in the gov.states.or.tax.income.credits.wfhdc.match parameter file do not always agree with the percentages in the cited references.  Here is a test case that illustrates the problem:

```
- name: Tax unit with taxsimid 93470 in g21.its.csv and g21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 62
        employment_income: 24010
        taxable_interest_income: 5505
        taxable_private_pension_income: 1500
        social_security_retirement: 1000
        rent: 15000
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person2:
        age: 62
        employment_income: 23010
        taxable_interest_income: 5505
        taxable_private_pension_income: 1500
        social_security_retirement: 1000
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person3:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person4:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person5:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4, person5]
        tax_unit_childcare_expenses: 10000
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
        tax_unit_itemizes: False
        state_income_tax: -650.12
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4, person5]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2, person3, person4, person5]
        state_fips: 41  # OR
  output:  # expected results from patched TAXSIM35 2024-01-31 version
    or_income_tax: 1849.88
    # PEUS computes -650.12, which is $2,500 different from the TAXSIM result
```
