### ISSUE TITLE
Fix Hawaii itemized deductions calculation

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3747]
In the 0.637.1 version, the HI itemized deductions amount is not always calculated correctly.   The problem is illustrated in the test case below and is described more analytically in this [PE-Core issue](https://github.com/PolicyEngine/policyengine-core/issues/150) .

```
- name: Tax unit with taxsimid 50310 in k21.its.csv and k21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 48
        employment_income: 131010
        qualified_dividend_income: 6010
        taxable_interest_income: 11010
        short_term_capital_gains: 3010
        long_term_capital_gains: 2010
        rental_income: 8010
        real_estate_taxes: 24000
        mortgage_interest: 1000
        self_employment_income: 139010
        business_is_qualified: true
        business_is_sstb: false
        w2_wages_from_qualified_business: 100e6
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1]
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1]
        state_fips: 15  # HI
  output:  # expected results from patched TAXSIM35 2024-01-31 version
    hi_income_tax: 22145.18
    # PEUS fails this test generating 24523.56
```
