### ISSUE TITLE
Fix Ohio credit calculations

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3750]
In the 0.637.2 version, some of the OH credits are being calculated incorrectly.   Below is a test case that illustrates two problems: (a) a missing senior citizen credit of $50 and (b) a missing exemption credit of $100.  TAXSIM35 gives this case both these credits, but Policyengine-US gives neither.

Here are the 2021 instructions that suggest TAXSIM35 is correct in this case:

<img width="475" alt="Screenshot 2024-02-01 at 10 52 34 AM" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/50ff5b10-74c4-455f-b72a-f9d52dc344d2">

And the exemption credit instructions say:

<img width="469" alt="Screenshot 2024-02-01 at 10 52 45 AM" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/d17d9b7c-98bb-4a23-a956-0120b8a425e1">

Here is the test case:

```
- name: Tax unit with taxsimid 96310 in e21.its.csv and e21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 69
        employment_income: 29010
        taxable_interest_income: 11010
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person2:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person3:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person4:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
      person5:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4, person5]
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4, person5]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2, person3, person4, person5]
        state_fips: 39  # OH
  output:  # expected results from patched TAXSIM35 2024-01-31 version
    oh_income_tax: 314.32
    # PEUS fails this test because it generates a value of $464.32, which is
    #   $150 more than TAXSIM35 generates
```

Part of the problem is being caused by this [Policyengine-Core issue](https://github.com/PolicyEngine/policyengine-core/issues/150).
