### ISSUE TITLE
Fix use of Arkansas low-income tax tables

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3856]
In the 0.652.0 version, it looks as if PEUS is allowing married filing separately individuals to
use the low-income tax tables, which is not allowed according to these 2021 instructions:

.
.
.

<img width="1457" alt="Screenshot 2024-02-12 at 1 48 50 PM" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/ba516a17-666c-4957-a1c1-0c260749beed">

.
.
.

<img width="1487" alt="Screenshot 2024-02-12 at 1 49 09 PM" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/3e19b684-fc0d-44ad-8cf4-700312fb7fab">

.
.
.

Here is an integration test that illustrates the problem:

```
- name: Tax unit with taxsimid 77552 in e21.its.csv and e21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 66
        employment_income: 14010
        taxable_interest_income: 5505.0
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person2:
        age: 66
        employment_income: 7010
        taxable_interest_income: 5505.0
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person3:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person4:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person5:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4, person5]
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
        ca_use_tax: 0  # not in TAXSIM35
        il_use_tax: 0  # not in TAXSIM35
        nm_2021_income_rebate: 0  # not in TAXSIM35
        nm_additional_2021_income_rebate: 0  # not in TAXSIM35
        nm_supplemental_2021_income_rebate: 0  # not in TAXSIM35
        ny_supplemental_eitc: 0  # not in TAXSIM35
        ok_use_tax: 0  # not in TAXSIM35
        pa_use_tax: 0  # not in TAXSIM35
        vt_renter_credit: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4, person5]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2, person3, person4, person5]
        state_fips: 5  # AR
  output:  # expected results from patched TAXSIM35 2024-02-09 version
    ar_income_tax: 687.03
```
