### ISSUE TITLE
Fix MT income tax model crash

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#3971]
In the 0.672.1 version, calculating the `mt_income_tax` variable causes the model to crash with the following fatal error message:

```
vars/gov/states/mt/tax/income/deductions/mt_head_deductions_exemptions_indiv.py"          
       line 21, in formula
         spouse_agi_attributed_to_head = tax_unit.sum(spouse_agi) * head
ValueError: operands could not be broadcast together with shapes (100000,) (279905,) 
```

**Please add an integration test that contains a tax unit with more than one person!**

**Comment by PavelMakarchuk** [comment]
I see the issue but I am unsure how the existing `mt_head_deductions_exemptions_indiv` does not catch that. 

```
- name: The AGI difference is attributed to the person with the higher AGI and the rest is halved
  period: 2021
  input:
    people: 
      person1:
        is_tax_unit_head: true
        mt_agi: 20_000
      person2:
        is_tax_unit_spouse: true
        mt_agi: 18_000
      person3:
        mt_agi: 0
    tax_units:
      tax_unit:
        members: [person1, person2, person3]
        mt_tax_unit_deductions_exemptions_indiv: 10_000
    households:
      household:
        members: [person1, person2, person3]
        state_code: MT
  output:
    mt_head_deductions_exemptions_indiv: 6_000
```
