### ISSUE TITLE
Remove rent from the list of Mississippi income sources

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/policyengine-us#4078]
We currently include rent to the list of Mississippi income sources, but it should be rental_income as rent represents rent payments. 
[Form](https://www.dor.ms.gov/sites/default/files/Forms/Individual/80100221.pdf#page=11) Line 41
![image](https://github.com/PolicyEngine/policyengine-us/assets/110687043/3d793672-9e2a-4b13-aa8a-16fc92cf907a)

Should pass the following test:
```
- name: Tax unit with taxsimid 99991 in g21.its.csv and g21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 64
        employment_income: 41010
        taxable_interest_income: 11010
        taxable_private_pension_income: 12000
        social_security_retirement: 19000
        rent: 24000
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person2:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2]
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
        ca_use_tax: 0  # not in TAXSIM35
        il_use_tax: 0  # not in TAXSIM35
        nm_2021_income_rebate: 0  # not in TAXSIM35
        nm_additional_2021_income_rebate: 0  # not in TAXSIM35
        nm_supplemental_2021_income_rebate: 0  # not in TAXSIM35
        ny_supplemental_eitc: 0  # not in TAXSIM35
        ok_use_tax: 0  # not in TAXSIM35
        pa_use_tax: 0  # not in TAXSIM35
        vt_renter_credit: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2]
        state_fips: 28  # MS
  output:  # expected results from patched TAXSIM35 2024-02-19 version
    ms_income_tax: 2286.00
```
