### ISSUE TITLE
Add short term capital gains to the Michigan household resources

### ISSUE THREAD

**Issue by Mshuning** [PolicyEngine/policyengine-us#4104]
According to the tax form, `short_term_capital_gains` should be included in the `mi_household_resources`:
https://www.michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/2022/2022-IIT-Forms/MI-1040CR.pdf#page=1
https://www.michigan.gov/taxes/-/media/Project/Websites/taxes/Forms/2022/2022-IIT-Forms/BOOK_MI-1040.pdf#page=15
![image](https://github.com/PolicyEngine/policyengine-us/assets/31402450/bc6acc6a-9739-4cea-b61d-a5460f612de4)

should fix the following test:
```
- name: Tax unit with taxsimid 97725 in h21.its.csv and h21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 37
        employment_income: 31010
        taxable_interest_income: 5505.0
        short_term_capital_gains: 5005.0
        rental_income: 2505.0
        rent: 23000
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person2:
        age: 37
        employment_income: 4010
        taxable_interest_income: 5505.0
        short_term_capital_gains: 5005.0
        rental_income: 2505.0
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2]
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
        ca_use_tax: 0  # not in TAXSIM35
        il_use_tax: 0  # not in TAXSIM35
        nm_2021_income_rebate: 0  # not in TAXSIM35
        nm_additional_2021_income_rebate: 0  # not in TAXSIM35
        nm_supplemental_2021_income_rebate: 0  # not in TAXSIM35
        ny_supplemental_eitc: 0  # not in TAXSIM35
        ok_use_tax: 0  # not in TAXSIM35
        pa_use_tax: 0  # not in TAXSIM35
        vt_renter_credit: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2]
        state_fips: 26  # MI
  output:  # expected results from patched TAXSIM35 2024-03-06 version
    mi_income_tax: 2178.13
```
