### ISSUE TITLE
Include the self employment deduction to the list of Michigan additions and remove the self employment income from the list of household resources

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/policyengine-us#4243]
From the Michigan homestead property tax [instructions](https://www.michigan.gov/-/media/Project/Websites/taxes/2022RM/IIT/MI1040CR_Instructions.pdf?rev=adf620bae4b447f7b6629cf8a639f556) 
![image](https://github.com/PolicyEngine/policyengine-us/assets/110687043/8bcc0cab-4971-4fbe-b296-8c02649f3d55)

Should fix the following:
```
- name: Tax unit with taxsimid 50656 in j21.its.csv and j21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 59
        employment_income: 2010
        qualified_dividend_income: 1005.0
        taxable_interest_income: 5505.0
        short_term_capital_gains: 3005.0
        long_term_capital_gains: 505.0
        rental_income: 2005.0
        taxable_private_pension_income: 3500.0
        rent: 24000
        self_employment_income: 10010
        business_is_qualified: true
        business_is_sstb: true
        w2_wages_from_qualified_business: 100e6
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person2:
        age: 59
        employment_income: 9010
        qualified_dividend_income: 1005.0
        taxable_interest_income: 5505.0
        short_term_capital_gains: 3005.0
        long_term_capital_gains: 505.0
        rental_income: 2005.0
        taxable_private_pension_income: 3500.0
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person3:
        age: 16
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2, person3]
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
        ca_use_tax: 0  # not in TAXSIM35
        il_use_tax: 0  # not in TAXSIM35
        nm_2021_income_rebate: 0  # not in TAXSIM35
        nm_additional_2021_income_rebate: 0  # not in TAXSIM35
        nm_supplemental_2021_income_rebate: 0  # not in TAXSIM35
        ny_supplemental_eitc: 0  # not in TAXSIM35
        ok_use_tax: 0  # not in TAXSIM35
        pa_use_tax: 0  # not in TAXSIM35
        vt_renter_credit: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2, person3]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2, person3]
        state_fips: 26  # MI
  output:  # expected results from patched TAXSIM35 2024-03-09 version
    mi_income_tax: 88.65
```
</div>
