### ISSUE TITLE
Fix Virginia low-income credit calculation

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#4260]
Using the 0.711.6 version, the amounts generated for the VA low-income credit are difficult to take seriously.   Below is a test case to which PEUS assigns a low-income credit of almost 1.4 million dollars.

```
- name: Tax unit with taxsimid 41750 in h21.its.csv and h21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 54
        employment_income: 14_010
        taxable_interest_income: 5_505
        short_term_capital_gains: 2_505
        rent: 20000
      person2:
        age: 54
        employment_income: 1_010
        taxable_interest_income: 5_505
        short_term_capital_gains: 2_505
      person3:
        age: 11
      person4:
        age: 11
      person5:
        age: 16
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4, person5]
        tax_unit_childcare_expenses: 3_000
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4, person5]
    households:
      household:
        members: [person1, person2, person3, person4, person5]
        state_fips: 51  # VA
  output:
   va_low_income_tax_credit: 1_395_000
```
