### ISSUE TITLE
Fix Kentucky deduction logic

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#4324]
In the 0.721.0 version, the KY itemized deduction logic is incorrect.
Here is what the 2021 form instructions say:

<img width="697" alt="Screenshot 2024-04-02 at 6 52 46 PM" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/f7c3c0e6-3119-4e01-ac81-4861a86412dd">

But the following simple test shows that Policyengine-US incorrectly allows each spouse to make their own decision between taking their standard deduction or their share of the couple's total itemized deductions.

```
- name: KY married couple with mortgage interest on their jointly owned home
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 50
        employment_income: 80_000
        mortgage_interest:  3_000
      person2:
        age: 50
        employment_income: 20_000
        mortgage_interest:  3_000
    tax_units:
      tax_unit:
        members: [person1, person2]
    spm_units:
      spm_unit:
        members: [person1, person2]
    households:
      household:
        members: [person1, person2]
        state_fips: 21  # KY
  output:
    ky_itemized_deductions_indiv: [4_800 , 1_200]
    ky_standard_deduction_indiv:  [2_690 , 2_690]
    # ky_deductions_indiv:        [4_800 , 2_690] PEUS produces this result
    # but that is illegal as the couple must make the same deduction decision
    ky_deductions_indiv:          [4_800 , 1_200] # this is the correct result
```
