### ISSUE TITLE
Adjust the Delaware elderly or disabled exclusion to represent the case where married couples file jointly

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/policyengine-us#4349]
Currently, both head and spouse have to be eligible to receive the exclusion but each person is checked independently and receives their own exclusion amount 

Should fix the following:
```
- name: Tax unit with taxsimid 2682 in h21.its.csv and h21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 64
        employment_income: 1010
        taxable_interest_income: 5505.0
        short_term_capital_gains: 4505.0
        rental_income: 3005.0
        taxable_private_pension_income: 6000.0
        social_security_retirement: 1500.0
        rent: 15000
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person2:
        age: 64
        employment_income: 61010
        taxable_interest_income: 5505.0
        short_term_capital_gains: 4505.0
        rental_income: 3005.0
        taxable_private_pension_income: 6000.0
        social_security_retirement: 1500.0
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person3:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2, person3]
        tax_unit_childcare_expenses: 2000
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
        ca_use_tax: 0  # not in TAXSIM35
        il_use_tax: 0  # not in TAXSIM35
        nm_2021_income_rebate: 0  # not in TAXSIM35
        nm_additional_2021_income_rebate: 0  # not in TAXSIM35
        nm_supplemental_2021_income_rebate: 0  # not in TAXSIM35
        ny_supplemental_eitc: 0  # not in TAXSIM35
        ok_use_tax: 0  # not in TAXSIM35
        pa_use_tax: 0  # not in TAXSIM35
        vt_renter_credit: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2, person3]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2, person3]
        state_fips: 10  # DE
  output:  # expected results from patched TAXSIM35 2024-04-04 version
    de_income_tax: 2429.20
```
