### ISSUE TITLE
Fix Delaware _joint variable calculations

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#4383]
In the 0.729.1 version, several `_joint` DE variables look to be miscalculated.

In the test case below, the trace output includes these variable values:

```
   [137485.92  2025.00  0.00] de_agi_joint
   [  9000.  2500.  0.] de_standard_deduction_joint
```

But the computational convention for `_joint` variables in all the states with  a "married filing separately on the same form" filing status, is to put the sum of the whole filing unit's amounts in the first vector position and put zeros in all the other vector positions.   Not doing that consistently in the DE income tax module leads to differences with TAXSIM35.   Here is an example:

```
- name: Tax unit with taxsimid 22359 in k21.its.csv and k21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 74
        employment_income: 24010
        taxable_interest_income: 5505.0
        short_term_capital_gains: 2505.0
        long_term_capital_gains: 1505.0
        taxable_private_pension_income: 4000.0
        social_security_retirement: 12000.0
        real_estate_taxes: 2000
        mortgage_interest: 1000
        self_employment_income: 121010
        business_is_qualified: true
        business_is_sstb: false
        w2_wages_from_qualified_business: 100e6
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person2:
        age: 74
        employment_income: 1010
        taxable_interest_income: 5505.0
        short_term_capital_gains: 2505.0
        long_term_capital_gains: 1505.0
        taxable_private_pension_income: 4000.0
        social_security_retirement: 12000.0
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person3:
        age: 16
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2, person3]
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
        ca_use_tax: 0  # not in TAXSIM35
        il_use_tax: 0  # not in TAXSIM35
        nm_2021_income_rebate: 0  # not in TAXSIM35
        nm_additional_2021_income_rebate: 0  # not in TAXSIM35
        nm_supplemental_2021_income_rebate: 0  # not in TAXSIM35
        ny_supplemental_eitc: 0  # not in TAXSIM35
        ok_use_tax: 0  # not in TAXSIM35
        pa_use_tax: 0  # not in TAXSIM35
        vt_renter_credit: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2, person3]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2, person3]
        state_fips: 10  # DE
  output:  # expected results from patched TAXSIM35 2024-04-11 version
    de_income_tax: 6882.22
```
