### ISSUE TITLE
Fix Delaware itemized deduction decision logic

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#4390]
In the 0.733.1 version, the tax unit's decision about whether or not to itemize DE deductions does not seem to be correct.   Here is some trace output for the integration test case included at the end of this comment:

```
stdded         [  5750.    5750.  ] de_standard_deduction_indv
                       [ 11500.       0.  ] de_standard_deduction_joint
itmded         [  2598.86   401.14] de_itemized_deductions_indv
                       [  3000.       0.  ] de_itemized_deductions_joint
deduction      [  5750.    5750.  ] de_deduction_indv
                       [  3000.       0.  ] de_deduction_joint
```

The first five lines in the above table make sense and are in agreement with TAXSIM35.
However, the last line is puzzling.   I fail to see why the couple filing jointly would choose to itemize (giving them only a $3,000 deduction) when they can use the $11,500 standard deduction.

This trace output is generated by the following test case:

```
- name: Tax unit with taxsimid 22359 in k21.its.csv and k21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 74
        employment_income: 24010
        taxable_interest_income: 5505.0
        short_term_capital_gains: 2505.0
        long_term_capital_gains: 1505.0
        taxable_private_pension_income: 4000.0
        social_security_retirement: 12000.0
        real_estate_taxes: 2000
        mortgage_interest: 1000
        self_employment_income: 121010
        business_is_qualified: true
        business_is_sstb: false
        w2_wages_from_qualified_business: 100e6
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person2:
        age: 74
        employment_income: 1010
        taxable_interest_income: 5505.0
        short_term_capital_gains: 2505.0
        long_term_capital_gains: 1505.0
        taxable_private_pension_income: 4000.0
        social_security_retirement: 12000.0
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person3:
        age: 16
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2, person3]
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
        ca_use_tax: 0  # not in TAXSIM35
        il_use_tax: 0  # not in TAXSIM35
        nm_2021_income_rebate: 0  # not in TAXSIM35
        nm_additional_2021_income_rebate: 0  # not in TAXSIM35
        nm_supplemental_2021_income_rebate: 0  # not in TAXSIM35
        ny_supplemental_eitc: 0  # not in TAXSIM35
        ok_use_tax: 0  # not in TAXSIM35
        pa_use_tax: 0  # not in TAXSIM35
        vt_renter_credit: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2, person3]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2, person3]
        state_fips: 10  # DE
  output:  # expected results from patched TAXSIM35 2024-04-11 version
    de_income_tax: 6882.22
```
