### ISSUE TITLE
Fix New York household credit calculation

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#4399]
Using the 0.736.0 version, the `ny_household_credit` variable seems to be miscalculated in some cases.   Consider the following simple test (which fails because PEUS calculates a credit of $110):

```
- name: Simple ny_household_credit test
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 40
      person2:
        age: 10
      person3:
        age: 11
      person4:
        age: 13
      person5:
        age: 15
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4, person5]
        adjusted_gross_income: 20_020
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4, person5]
    households:
      household:
        members: [person1, person2, person3, person4, person5]
        state_fips: 36  # NY
  output:  # from 2021 NY IT-213 instructions lookup table on page 20
    ny_household_credit: 100
```

The expected result is obtained from this table:

<img width="1231" alt="NY-hh-credit" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/e57eb5d0-43e9-4240-b308-9cfc5baecd66">
