### ISSUE TITLE
Fix Delaware itemized deduction split between married filing separately

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#4400]
In the 0.736.0 version, the `de_itemized_deductions_indv` variable does not seem to be calculated correctly in all cases.   The following test fails (because PEUS calculates a different allocation of the itemized deductions total):

```
- name: test allocation of DE itemized deductions when married filing separately
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 70
        employment_income: 6010
        qualified_dividend_income: 2505.0
        taxable_interest_income: 5505.0
        short_term_capital_gains: 4005.0
        long_term_capital_gains: 3505.0
        taxable_private_pension_income: 5000.0
        social_security_retirement: 12000.0
        real_estate_taxes: 10000
        mortgage_interest: 34000
        self_employment_income: 128010
        business_is_qualified: true
        business_is_sstb: false
        w2_wages_from_qualified_business: 100e6
      person2:
        age: 70
        qualified_dividend_income: 2505.0
        taxable_interest_income: 5505.0
        short_term_capital_gains: 4005.0
        long_term_capital_gains: 3505.0
        taxable_private_pension_income: 5000.0
        social_security_retirement: 12000.0
    tax_units:
      tax_unit:
        members: [person1, person2]
    spm_units:
      spm_unit:
        members: [person1, person2]
    households:
      household:
        members: [person1, person2]
        state_fips: 10  # DE
  output:  # expected results from patched TAXSIM35 2024-04-15 version
    adjusted_gross_income_person: [155696.38 , 30720.00]
    de_itemized_deductions_unit: 44000
    de_itemized_deductions_indv: [38561.50 , 5438.50]
```
