### ISSUE TITLE
Fix Mississippi taxable income calculations

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#4404]
In the 0.739.0 version (after PR #4329 was merged), the `ms_taxable_income_indiv` variable is not always correctly calculated.  Here are excerpts from the trace output for the test case that is presented below:

```
TAXSIM35 SITax Summary:    PEUS Trace Output
AGI              89060.00  [78030. 11030.] ms_agi
exemptions       18000.00  [ 9000.  9000.] ms_total_exemptions_indiv
                           [18000.     0.] ms_total_exemptions_joint
stdded            4600.00  [ 2300.  2300.] ms_deductions_indiv
                           [ 4600.     0.] ms_deductions_joint
taxinc           66460.00  [66730.     0.] ms_taxable_income_indiv
                           [55430. 11030.] ms_taxable_income_joint
                                   ^^^^^
```

Here is the test case:

```
- name: Tax unit with taxsimid 90168 in i21.its.csv and i21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 31
        employment_income: 68010
        qualified_dividend_income: 2505.0
        taxable_interest_income: 5505.0
        long_term_capital_gains: 1005.0
        rental_income: 1005.0
        rent: 2000
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person2:
        age: 31
        employment_income: 1010
        qualified_dividend_income: 2505.0
        taxable_interest_income: 5505.0
        long_term_capital_gains: 1005.0
        rental_income: 1005.0
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person3:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person4:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person5:
        age: 16
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person6:
        age: 16
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4, person5, person6]
        tax_unit_childcare_expenses: 2000
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
        ca_use_tax: 0  # not in TAXSIM35
        il_use_tax: 0  # not in TAXSIM35
        nm_2021_income_rebate: 0  # not in TAXSIM35
        nm_additional_2021_income_rebate: 0  # not in TAXSIM35
        nm_supplemental_2021_income_rebate: 0  # not in TAXSIM35
        ny_supplemental_eitc: 0  # not in TAXSIM35
        ok_use_tax: 0  # not in TAXSIM35
        pa_use_tax: 0  # not in TAXSIM35
        vt_renter_credit: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4, person5, person6]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2, person3, person4, person5, person6]
        state_fips: 28  # MS
  output:  # expected results from patched TAXSIM35 2024-04-15 version
    ms_income_tax: 3053.00
```
