### ISSUE TITLE
Fix Arkansas capital gains calculation

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#4413]
The 0.741.1 version does not seem to calculate the `ar_taxable_capital_gains` variable correctly.
There need to be more unit tests to test handling of various kinds of losses.

Here is a simple unit test that illustrates the problem:

```
- name: AR taxable capital gains unit test 1
  absolute_error_margin: 0.01
  period: 2021
  input:
    short_term_capital_gains: 800
    state_fips: 5  # AR
  output:  # AR 1000D form says all short-term capital gains are taxable
    ar_taxable_capital_gains: 800
```

PEUS fails this test calculating the variable's value as $400.
