### ISSUE TITLE
Fix Mississippi itemized deductions calculation

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#4426]
In the 0.743.0 version, the formula for the `ms_itemized_deductions_unit` variable is incorrect.

Even a very simple unit test reveals this formula is incorrect (because it produces $36,000):

```
- name: MS itemized deductions unit test 1
  absolute_error_margin: 0.01
  period: 2021
  input:
    real_estate_taxes: 12_000
    mortgage_interest: 36_000
    state_fips: 28  # MS
  output:  # expected results from filling out 2021 MS form 80-108
    ms_itemized_deductions_unit: 46_000
```
