### ISSUE TITLE
Fix Arkansas capital gain loss cap parameter values

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#4443]
The 2021 AR1000D form says this in RED:

<img width="1271" alt="Screenshot 2024-04-23 at 3 45 42 PM" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/600722cc-7eaf-4b92-ae03-ad4eb59f8df5">

.
.

But the following `loss_cap.yaml` file has different values:

https://github.com/PolicyEngine/policyengine-us/blob/c64a7a20ac62a8544df3c45697d9842ca4cdefb1/policyengine_us/parameters/gov/states/ar/tax/income/gross_income/capital_gains/loss_cap.yaml#L1-L29

.
.
As a result, Policyengine-US 0.749.1 fails the following simple unit test:

```
- name: AR taxable capital gains unit test 2
  absolute_error_margin: 0.01
  period: 2021
  input:
    filing_status: SINGLE
    long_term_capital_gains: -4_000
    state_fips: 5  # AR
  output:  # expected results from filing out 2021 AR1000D form
    ar_taxable_capital_gains: -3_000
```
