### ISSUE TITLE
snap_standard_deduction does not calculate year value correctly.

### ISSUE THREAD

**Issue by CalebPena** [PolicyEngine/policyengine-us#4502]
The following test passes:
```yaml
- name: Month
  period: 2024-1
  input:
    state_group: CONTIGUOUS_US
  output:
    snap_standard_deduction: 198
```

But this one fails:
```yaml
- name: Year
  period: 2024
  input:
    state_group: CONTIGUOUS_US
  output:
    snap_standard_deduction: 2_376 # 198 * 12
```

**Comment by CalebPena** [comment]
I am pretty sure that this has to do with uprating, because when I remove it both tests pass.

**Comment by MaxGhenis** [comment]
Yes, we project the standard deduction increase scheduled for October.

**Comment by CalebPena** [comment]
Okay, that makes sense, but I get an error when I try:
```yaml
- name: Month
  period: 2024-10
  input:
    state_group: CONTIGUOUS_US
  output:
    snap_standard_deduction: 198
```
