### ISSUE TITLE
Fix Virginia itemized deduction limitation logic

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#4505]
In the 0.766.0 version, it seems as if the VA itemized deduction calculations are incorrect.   The case presented below illustrate what seem to me to be the problem.

The case has high AGI so its VA itemized deductions are limited on the limitation worksheet.
The case has mortgage interest of $14K and local property taxes of $24K.  TAXSIM35 assumes this case fills out its federal Schedule A by claiming zero state income tax and $14K property taxes (the sum of which is capped at $10K on the federal form), in order to maximize its VA itemized deductions.   This means that on the VA Schedule A, line 5a is zero and line 5b is $24K and line 10 is $14K.  That means TAXSIM35 thinks this case fills out the Virginia LIMITED ITEMIZED DEDUCTION WORKSHEET as follows:
```
  xlin1,xlin2   38000.000000000000        0.0000000000000000     
  PRE-LIMIT xitded    38000.000000000000     
  law,AGIthd        2021   334150.00000000000     
  xlin3,xlin4   38000.000000000000        30400.000000000000     
  xlin8,xlin9   950.18374199325388        950.18374199325388     
  xlin11,alin17   2.5004835315611942E-002   37049.816258006744     
  xlin13,xlin14   0.0000000000000000        0.0000000000000000     
  alin18   0.0000000000000000     
  POST-LIMIT xitded    37049.816258006744     
```

Tracing the internal calculation of the `va_reduced_itemized_deductions` formula reveals that PEUS fills out the SCHEDULE starting with line 1 (xlin1) being $24K (not $38K).   I don't see how this can be correct.  I am missing something?

Here is the tax unit case:

```
- name: Tax unit with taxsimid 5034 in k21.its.csv and k21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 54
        employment_income: 137010
        qualified_dividend_income: 3505.0
        taxable_interest_income: 5505.0
        long_term_capital_gains: 1005.0
        rental_income: 2505.0
        real_estate_taxes: 24000
        mortgage_interest: 14000
        self_employment_income: 141010
        business_is_qualified: true
        business_is_sstb: false
        w2_wages_from_qualified_business: 100e6
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person2:
        age: 54
        employment_income: 65010
        qualified_dividend_income: 3505.0
        taxable_interest_income: 5505.0
        long_term_capital_gains: 1005.0
        rental_income: 2505.0
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person3:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person4:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4]
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
        ca_use_tax: 0  # not in TAXSIM35
        il_use_tax: 0  # not in TAXSIM35
        nm_2021_income_rebate: 0  # not in TAXSIM35
        nm_additional_2021_income_rebate: 0  # not in TAXSIM35
        nm_supplemental_2021_income_rebate: 0  # not in TAXSIM35
        ny_supplemental_eitc: 0  # not in TAXSIM35
        ok_use_tax: 0  # not in TAXSIM35
        pa_use_tax: 0  # not in TAXSIM35
        vt_renter_credit: 0  # not in TAXSIM35
        tax_unit_itemizes: False
        state_income_tax: 20045.91
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2, person3, person4]
        state_fips: 51  # VA
  output:  # expected results from patched TAXSIM35 2024-05-07 version
    va_income_tax: 18433.05
```
