### ISSUE TITLE
Fix Virginia itemized deduction logic

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#4552]
Using the 0.777.2 version, the VA itemized deduction logic allows itemization when not itemizing on the federal return.  But that is against the VA tax rules as can be seen in this part of the intructions:

<img width="381" alt="Screenshot 2024-05-23 at 6 20 33 PM" src="https://github.com/PolicyEngine/policyengine-us/assets/12170745/af8b7509-60d6-489f-bca5-769b4570e534">

.

This problem shows up in many cases, of which this is one:

```
- name: Tax unit with taxsimid 46086 in k21.its.csv and k21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 59
        employment_income: 138010
        qualified_dividend_income: 1005.0
        taxable_interest_income: 5505.0
        short_term_capital_gains: 4005.0
        long_term_capital_gains: 1005.0
        rental_income: 5005.0
        taxable_private_pension_income: 3000.0
        real_estate_taxes: 22000
        mortgage_interest: 10000
        self_employment_income: 159010
        business_is_qualified: true
        business_is_sstb: true
        w2_wages_from_qualified_business: 100e6
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person2:
        age: 59
        employment_income: 26010
        qualified_dividend_income: 1005.0
        taxable_interest_income: 5505.0
        short_term_capital_gains: 4005.0
        long_term_capital_gains: 1005.0
        rental_income: 5005.0
        taxable_private_pension_income: 3000.0
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person3:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person4:
        age: 16
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4]
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
        ca_use_tax: 0  # not in TAXSIM35
        il_use_tax: 0  # not in TAXSIM35
        nm_2021_income_rebate: 0  # not in TAXSIM35
        nm_additional_2021_income_rebate: 0  # not in TAXSIM35
        nm_supplemental_2021_income_rebate: 0  # not in TAXSIM35
        ny_supplemental_eitc: 0  # not in TAXSIM35
        ok_use_tax: 0  # not in TAXSIM35
        pa_use_tax: 0  # not in TAXSIM35
        vt_renter_credit: 0  # not in TAXSIM35
        tax_unit_itemizes: True
        state_income_tax: 18412.69
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2, person3, person4]
        state_fips: 51  # VA
  output:  # expected results from patched TAXSIM35 2024-05-23 version
    va_income_tax: 19691.19
```

Here is how TAXSIM35 handles this case:
```
 --ided,fsded,fided,fitax           1           0       20000       59677
   schild,ssded,sided           0        9000       31234
   deduc,statax,titax       31234       18412       78089
 --ided,fsded,fided,fitax           1           0       20000       59677
   schild,ssded,sided           0        9000       31234
   deduc,statax,titax       31234       18412       78089
 --ided,fsded,fided,fitax           0       25100       20000       58070
   schild,ssded,sided           0        9000           0
   deduc,statax,titax        9000       19691       77761
 --ided,fsded,fided,fitax           0       25100       20000       58070
   schild,ssded,sided           0        9000           0
   deduc,statax,titax        9000       19691       77761
```

So, federal plus state income taxes are minimized by using the standard deduction on both forms (rather than itemizing on both forms).   Note that that `ided` variable is a zero/one integer indicating federal itemization.
