### ISSUE TITLE
Fix snap_region formula

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#4842]
While investigating the possible causes of the three microsimulation test errors experienced in PR #4840, I found that there were no unit tests for the `snap_region` variable.   When adding six unit tests, I find there is one test failure.  I don't think this test failure explains the microsimulation test errors in PR #4840, but it does seem to generate incorrect SNAP benefits because people living in Alaska are incorrectly considered to be living in the contiguous US.

Here is the `snap_region.yaml` test file:
```
#class StateGroup(Enum):
#    CONTIGUOUS_US = "Contiguous US"
#    AK = "Alaska"
#    HI = "Hawaii"
#    GU = "Guam"
#    PR = "Puerto Rico"
#    VI = "Virgin Islands"
#    # Omit other territories for now.
    
- name: snap_region unit test 1
  period: 2020
  absolute_error_margin: 0
  input:
    state_group: CONTIGUOUS_US
  output:
    snap_region: CONTIGUOUS_US

- name: snap_region unit test 2
  period: 2020
  absolute_error_margin: 0
  input:
    state_group: AK
  output:
    snap_region: AK_URBAN

- name: snap_region unit test 3
  period: 2020
  absolute_error_margin: 0
  input:
    state_group: HI
  output:
    snap_region: HI

- name: snap_region unit test 4
  period: 2020
  absolute_error_margin: 0
  input:
    state_group: GU
  output:
    snap_region: GU

- name: snap_region unit test 5
  period: 2020
  absolute_error_margin: 0
  input:
    state_group: PR
  output:
    snap_region: CONTIGUOUS_US

- name: snap_region unit test 6
  period: 2020
  absolute_error_margin: 0
  input:
    state_group: VI
  output:
    snap_region: VI
```

These test were executed in the following environment:
```
% pip list | grep policyengine
policyengine-core             2.21.8
policyengine-us               1.42.0
```

Here are the test results:
```
============================== FAILURES ===================================
____________________________ test session _________________________________
/Users/mrh/.../snap_region.yaml:
  Test 'snap_region unit test 2':
    snap_region@2020: ['CONTIGUOUS_US'] differs from AK_URBAN.
====================== short test summary info ============================
FAILED snap_region.yaml::
==================== 1 failed, 5 passed in 4.17s ==========================
```
