### ISSUE TITLE
Fix OAP for married people who both qualify for SSI.

### ISSUE THREAD

**Issue by CalebPena** [PolicyEngine/policyengine-us#5275]
Currently PE assigns SSI for married couples who both qualify for SSI to one of the members. This results in OAP being 0 for one member and full for the other. Instead, we should use half of the couple's SSI amount for each member of the marital unit.

**Comment by CalebPena** [comment]
@MaxGhenis @PavelMakarchuk Here is some more context for this issue:

For a household were both members of a marital unit are eligible for SSI, currently all of the income is given to one member of the marital unit. This is the incorrect way to handle this according to the [handbook](https://www.ssa.gov/OP_Home/handbook/handbook.01/handbook-0131.html).

Here is a test that can be used to see how SSI is currently handled for members of a marital unit.
```yaml
- name: Multiple people eligible
  period: 2024
  input:
    people:
      head:
        is_ssi_aged_blind_disabled: true
      spouse:
        is_ssi_aged_blind_disabled: true
    tax_units:
      tax_unit:
        members: [head, spouse]
    marital_units:
      marital_unit:
        members: [head, spouse]
  output:
    ssi: [0, 0]
```

We also compiled some more detailed notes [here](https://docs.google.com/document/d/1D-pKsKqNIRhu7ksXIcAXMHBH9aX-g_-Nz9dgx2T8pmo/edit?usp=sharing) including some of our conversations with CDHS and some examples.

This leads to issues with the state supplement (at least in Colorado) where the spouse might get OAP/AND-CS when they should not because we are saying that they have no SSI.

The current pr that I made simply splits the SSI for the marital couple when calculating the state supplements in Colorado, but it might be a better solution to split it at the SSI level given the handbook says married couples will receive separate checks if they are both eligible for SSI.
