### ISSUE TITLE
US tax filing requirement

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#5724]
### Background

PolicyEngine does not currently determine whether a taxpayer **must file** a federal return, but the Internal Revenue Code (IRC) and corresponding regulations outline specific rules for individuals.  
- **26 U.S.C. § 6012** sets out **gross‐income thresholds** (varying by filing status, age, etc.) above which an individual must file.  
- **26 CFR 1.6012‑1** elaborates on these thresholds and exceptions (e.g., married filing jointly, nonresident aliens, etc.).  

**26 U.S.C. § 6011(a)** states that if “*required by regulations prescribed by the Secretary*,” a person made liable for a tax must file—so we look to **26 CFR Part 1** (especially **1.6012‑1**) to see *how* and *when* individuals are required to file. There is no specific language in § 6011 or 1.6011–1 that says “if your net tax calculation is > \$0, you must file.” Instead, the regulations implement the requirement primarily through **gross‐income thresholds** and certain special circumstances (like being a nonresident alien engaged in a U.S. trade or business).

In practice, the IRS also uses its **Form 1040 Instructions** to clarify that you must file if you owe specific special taxes—*even when* below standard thresholds. But the Code and CFR sections themselves focus on *gross income* definitions, certain types of income (e.g., from outside the U.S.), and filing status rules.

---

### What We Need to Implement

1. **Base Filing Thresholds**  
   - Pull in the **current** (2023, etc.) **gross‐income thresholds** from § 6012 (and 26 CFR 1.6012‑1) for each filing status.  
   - If the taxpayer’s **gross income** exceeds that threshold, they must file.

2. **Special Cases from Regulations**  
   - For nonresident aliens, partial‐year residents, and others, the CFR lays out additional triggers that often require filing even below typical thresholds.  
   - E.g., “every nonresident alien individual…engaged in trade or business in the U.S.” in **26 CFR 1.6012‑1(b)(1)**.

3. **Implementation**  
   - Add a variable like `meets_federal_filing_requirement` that is **true** if *any* of the regulatory triggers occur.  
   - At minimum, implement the gross‐income thresholds from § 6012; add logic for the special cases from 1.6012–1 as needed.

4. **No Explicit “If You Owe Any Tax, You Must File” in Code/Regs**  
   - The statutes and regs revolve around *gross income* and certain specific conditions (e.g., nonresident alien rules).  
   - While the IRS instructions say you must file if you owe certain special taxes (like AMT, household employment tax, recapture, etc.), that requirement is a matter of **IRS guidance** interpreting multiple Code provisions.  
   - We can reflect that **guidance** if desired, but the direct text of § 6012 and CFR 1.6012–1 focuses primarily on income amounts and specific statuses.

---

### Proposed Implementation Steps

1. **Define** the `federal_filing_threshold` based on filing status, age, and any other relevant parameters for the given tax year (matching the Code/CFR/IRS annual updates).  
2. **Compare** the tax unit’s computed “gross income” with the threshold.  
3. **Set** `meets_federal_filing_requirement = true` if gross income ≥ threshold **or** if they meet any special conditions in the CFR (e.g., nonresident alien engaged in U.S. business).  
4. **Optionally**, to align with IRS instructions (though not spelled out in these specific sections of the Code/CFR):  
   - Mark `meets_federal_filing_requirement = true` if the household would owe certain taxes (such as AMT or recapture).  
   - However, this goes beyond the literal text of §§ 6011 and 6012, which do not explicitly say “Calculate your net tax, and if it’s above \$0, you must file.” Instead, that approach is primarily from the instructions that incorporate multiple sections of the IRC.

---

### Sample Tests

Below are some YAML examples. Adjust naming/fields as needed:

```yaml
- name: Single exactly at threshold
  period: 2023
  input:
    filing_status: SINGLE
    fed_agi: 13_850  # Example threshold
  output:
    meets_federal_filing_requirement: true

- name: Single below threshold, no special conditions
  period: 2023
  input:
    filing_status: SINGLE
    fed_agi: 10_000
  output:
    meets_federal_filing_requirement: false

- name: Nonresident alien with US business
  period: 2023
  input:
    filing_status: SINGLE
    fed_agi: 500  # Could be any amount
    # Nonresident alien scenario in which 1.6012-1(b)(1) triggers
  output:
    meets_federal_filing_requirement: true

- name: Married joint above threshold
  period: 2023
  input:
    filing_status: JOINT
    fed_agi: 30_000
  output:
    meets_federal_filing_requirement: true
```

---

### Next Steps

- **Implement** the threshold logic for each filing status in line with §§ 6012 and 26 CFR 1.6012–1.  
- **Add** special checks for the core cases spelled out in the CFR (nonresident aliens, etc.).  
- **Optionally** incorporate the *IRS Instructions approach* for special taxes if we want to match how the IRS instructs filers—though that guidance is not explicitly enumerated in the statutory or CFR text above.
