### ISSUE TITLE
Create independent checks for the EAEDC and TAFDC values

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/policyengine-us#5908]
We should have 3 new variables
`ma_tafdc_if_eaedc_ineligible` - checks the amount of tafdc if eaedc is 0
`ma_eaedc_if_tafdc_ineligible` - checks the amount of eaedc if tafdc 0 
`ma_tafdc_larger_than_eaedc` - checks whether `ma_tafdc_if_eaedc_ineligible`  > `ma_eaedc_if_eaedc_ineligible` 

Both `ma_eaedc` and `ma_tafdc` should be defined for `ma_tafdc_larger_than_eaedc` 

This will allow us to have mutual exclusivity based on the programs

**Comment by PavelMakarchuk** [comment]
We can use this as an integration test:
```
- name: Integration test, pregnant single parent with rent
  period: 2025-01
  input:
    people:
      person1:
        age: 19
        is_pregnant: true
        employment_income: 9_600
        rent: 1_200
        weekly_hours_worked_before_lsr: 13.3
      person2:
        age: 4
    spm_units:
      spm_unit:
        members: [person1, person2]
        ma_eaedc_living_arrangement: A
    tax_units:
      tax_unit:
        members: [person1, person2]
    households:
      household:
        members: [person1, person2]
        state_code: MA
        #is_in_public_housing: true
  output:
    ma_tcap_gross_earned_income: 
    ma_tafdc_countable_earned_income: 
    ma_tafdc_applicable_income_grant_amount:
    ma_tafdc_eligible:
    ma_tafdc_payment_standard: 
    ma_tafdc_eligible_dependent: 
    ma_tafdc_dependent_care_deduction: 
    ma_tafdc: 
    ma_eaedc_eligible:
    ma_eaedc_immigration_status_eligible:
    ma_eaedc_financial_eligible: 
    ma_eaedc_non_financial_eligible:
    ma_eaedc_income_eligible:
    ma_eaedc_assets_limit_eligible:
    ma_eaedc_standard_assistance:
    ma_eaedc_net_income: 
    # ma_eaedc_living_arrangement: 
    ma_eaedc: 
```
