### ISSUE TITLE
Bug — LSR flips sign when baseline earnings < 0

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-us#6053]
When a person has **negative baseline earnings** (usually a Schedule C loss), each labor-supply response formula multiplies that negative value by a positive elasticity and a positive percentage change:

```python
earnings * income_change * income_elasticity          # income_elasticity_lsr
earnings * wage_change   * substitution_elasticity    # substitution_elasticity_lsr
````

Because `earnings < 0`, the response’s sign reverses.
In the SNAP-repeal simulation this produces **falling high-income labor supply even though every unit gains in static terms**:

* 📈 Dynamic impact with LSR (note the negative income-effect bar):
  [https://policyengine.org/us/policy?focus=policyOutput.laborSupplyImpact.earnings.byDecile.relative.income\&reform=85253\&region=us\&timePeriod=2025\&baseline=2\&dataset=enhanced\_cps](https://policyengine.org/us/policy?focus=policyOutput.laborSupplyImpact.earnings.byDecile.relative.income&reform=85253&region=us&timePeriod=2025&baseline=2&dataset=enhanced_cps)

* 🟢 Static winners & losers (nobody loses):
  [https://policyengine.org/us/policy?focus=policyOutput.winnersAndLosers.incomeDecile\&reform=77230\&region=us\&timePeriod=2025\&baseline=2\&dataset=enhanced\_cps](https://policyengine.org/us/policy?focus=policyOutput.winnersAndLosers.incomeDecile&reform=77230&region=us&timePeriod=2025&baseline=2&dataset=enhanced_cps)

### Proposed fix (minimal)

1. Clip `earnings` at zero (or a tiny ε) **before** multiplying by elasticities.
2. Use a helper for safe division when computing earnings shares.

```python
EPS = 1e-3
def pos(x):          # clip negatives to zero
    return np.where(x <= 0, 0.0, x)

def safe_share(num, denom):
    return np.where(denom > 0, num / denom, 0.0)

# in income_elasticity_lsr and substitution_elasticity_lsr
earnings = pos(emp_income + se_income)
...
```

### Regression test

Add a YAML test that sets baseline self-employment income to a loss.
After clipping, the labor-supply response should be **non-negative**.

```yaml
- name: Negative earnings should not reduce labor supply
  period: 2025
  input:
    # Person-specific inputs
    self_employment_income: -10_000     # baseline loss
    employment_income: 0
    other_income: 50_000
    # Model parameters (elasticities > 0 to trigger the bug)
    gov.simulation.labor_supply_responses.elasticities.income: 0.05
    gov.simulation.labor_supply_responses.elasticities.substitution.all: 0.1
  output:
    labor_supply_behavioral_response: ">= 0"
```

> The expected value need not be exact—just assert it is **≥ 0**, confirming that the sign reversal is gone once clipping is in place.
