### ISSUE TITLE
Incorrect federal qualified_business_income formula

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#903]
The documentation and formula for the `qualified_business_income` variable need to be improved.   The documentation text is confusing and there are two problems with the formula.

The documentation conflates two different concepts:  (1) whether or not business income is qualified, and (2) whether or not qualified business income is from a specified service or trade business (SSTB).  Look at the IRS Publication 535 or Form 8995 for 2018 or later to see the distinction.   The SSTB/non-SSTB status of qualified business income affects how the qualified business income deduction (QBID) amount is phased out.  If business income is not qualified, it is not eligible for a QBID of any amount.  

The **first problem with the formula** is that it assumes the QBID calculation is conducted at the tax_unit level, when in should be conducted at the person level.  Legally, it is conducted at the business level with the forms being designed for each person in the tax_unit having more than one business.   Given the data typically available to OpenFisca-US users, it would be sensible to assume that each individual in a tax_unit has business income from at most one business.  That is the simplifying assumption made by [TAXSIM35](https://users.nber.org/~taxsim/taxsim35/), which has three business income variables for the taxpayer and three for the spouse.  The three TAXSIM35 input variables are:
- non-qualified business income (`?semp`),
- qualified business income that is from a non-SSTB (`?businc`), and
- qualified business income that is from a SSTB (`?profinc`).

The **second problem with the formula** is that it fails to subtract from gross business income the ALD amounts that are related to the business for which the QBID is being computed.  So, for example, the current formula subtracts neither the `self_employment_tax_ald` nor the `self_employed_health_insurance_ald` amounts from the gross qualified business income.  That this is what is supposed to happen can be seen when using TurboTax to work though a test case or when looking at the following `qualified_business_income` example provided by [Drake Software](https://www.drakesoftware.com/):

<img width="1094" alt="Drake19-QBI-SchC-logic" src="https://user-images.githubusercontent.com/12170745/173254636-4dac8905-37f6-4b47-90ea-cc8fdbfa60f6.png">

Here is a test case that fails because of this second problem with the formula:

```
(openfisca-us) OpenFisca-US% cat i19-id14.test.yaml
# OpenFisca-US test file derived from i19.its.csv and i19.ots.csv files
# Expected test output from NBER TAXSIM Model v35 (06/06/22) With TCJA

- name: Tax unit with taxsimid 14 from i19.its.csv
  absolute_error_margin: 0.01
  period: 2019
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 45
        self_employment_income: 285000
        business_is_qualified: true
        w2_wages_from_qualified_business: 1e6
    tax_units:
      tax_unit:
        members: [person1]
        premium_tax_credit: 0
    households:
      household:
        members: [person1]
        state_code: TX
  output:
    taxsim_tfica: 24681.10
    #tax_unit_taxable_unemployment_compensation: 0.00
    #tax_unit_taxable_social_security: 0.00
    #adjusted_gross_income: 272943.84
    #taxable_income: 208595.07
    #cdcc: 0.00
    #non_refundable_ctc: 0.00
    #refundable_ctc: 0.00
    #eitc: 0.00
    qualified_business_income: 272943.84
    qualified_business_income_deduction: 52148.77
    income_tax: 48201.77

(openfisca-us) OpenFisca-US% openfisca-us test i19-id14.test.yaml 
---[SNIP]---
/Users/.../OpenFisca-US/i19-id14.test.yaml:
  Test 'Tax unit with taxsimid 14 from i19.its.csv':
    qualified_business_income@2019: [285000.] differs from 272943.84375 
    with an absolute margin [12056.156] > 0.01
---[SNIP]---
======================= 1 failed in 0.05s ========================
```
