### ISSUE TITLE
Fix misunderstanding of taxable short-term capital gains under MA income tax

### ISSUE THREAD

**Issue by martinholmer** [PolicyEngine/policyengine-us#929]
First, before focusing on the issue in the title, let me say that the MA income tax capabilities in OpenFisca-US are quite impressive.  The capabilities were developed from reading the MA tax legislation in just a few days time.   I have tested thousands of randomly-generated cases and found no difference in the MA income tax liability generated by OpenFisca-US and the liability generated by TAXSIM35 and by my Massachusetts income Tax Analyzer.

But I have found some test cases for which the MA income tax generated by OpenFisca-US is different from the tax generated by the other two models (which are in agreement).  This issue presents one such case.  After showing the case and the tax difference, I explain the source of the difference.

Consider this test case:
```
# OpenFisca-US test file derived from k21.its.csv and k21.ots.csv files
# Expected test output from NBER TAXSIM Model v35 (06/14/22) With TCJA

- name: Tax unit with taxsimid 8 from k21.its.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 52
        employment_income: 74000
        short_term_capital_gains: 25000
        long_term_capital_gains: 35000
        rent: 7000
    tax_units:
      tax_unit:
        members: [person1]
        premium_tax_credit: 0
    households:
      household:
        members: [person1]
        state_code: MA
  output:
    taxsim_tfica: 5661.00
    #tax_unit_taxable_unemployment_compensation: 0.00
    #tax_unit_taxable_social_security: 0.00
    #adjusted_gross_income: 134000.00
    #taxable_income: 121450.00
    #cdcc: 0.00
    #non_refundable_ctc: 0.00
    #refundable_ctc: 0.00
    #eitc: 0.00
    income_tax: 20019.00
    ma_income_tax: 7980.00
```

Here are the test results:
```
============================ FAILURES ============================
__________________________ test session __________________________
/Users/mrh/work/OpenFisca-US/MA/k21-id8.test.yaml:
  Test 'Tax unit with taxsimid 8 from k21.its.csv':
    ma_income_tax@2021: [5880.] differs from 7980.0 
    with an absolute margin [2100.] > 0.01
==================== short test summary info =====================
FAILED k21-id8.test.yaml::
======================= 1 failed in 0.66s ========================
```

So, OpenFisca-US (0.74.1 version) generates a MA tax that is $2100 less than the tax generated by the other two models even though it correctly calculates the federal income tax for this case.

After looking at the OpenFisca-US trace output and comparing that with detailed output from my MA Analyzer, I think the source of the difference is the misunderstanding mentioned in the title of this issue.  OpenFisca-US thinks that half of **all** long-term capital gains can be subtracted from short-term capital gains, when in fact only half of long-term capital gains **on collectibles** (such as stamp collections or coin collections) can be deducted from short-term capital gains.  Reading the 2021 MA Form 1 and its instructions makes that clear.  Here is the part of the [MA tax legislation](https://www.mass.gov/info-details/mass-general-laws-c62-ss-2) that was misunderstood:

> (3) A deduction equal to 50 per cent of the gain income from the sale
> or exchange of property defined under **section 408(m)(2) of the Code**,
> as amended and in effect for the taxable year, and held for more than
> 1 year, after reduction by any losses in paragraph (2).  **[emphasis added]**

Section 408(m)(2) is the part of the US Internal Revenue Code where collectible assets are defined.

How this gets fixed is up to the OpenFisca-US developers.  TAXSIM35 and my MA Analyzer simply assume there will never be survey information about collectibles, and so, MA Form 1 Schedule B line 11 is always zero.  

Another approach would be to correct the wording in `parameters/gov/states/ma/tax/income/capital_gains/long_term_deduction.yaml`, add a long-term capital-gains-on-collectibles variable, and correct the calculation of the `long_term_gains_deduction` local variable in the `variables/gov/states/ma/tax/income/adjusted_gross_income/ma_part_a_agi.py` formula.
